### ISSUE TITLE
Error in docstring of CanICA `score` function.

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1081]
Where is the `per_component` argument that is mentioned in the `Returns` section of the score function?
http://nilearn.github.io/modules/generated/nilearn.decomposition.CanICA.html#nilearn.decomposition.CanICA.score

**Comment by bthirion** [comment]
It is defined in the base.py module for the BaseDecomposition class, from which Canica inherits.
2 possibilities: 
1. Either leave the code as is and remove any mention of it in the docstrings
2. Or change the code so that per_components is transferred to the score function
I don't use this code regularly so I have no strong opinion. I am rather in favor of 1: let's simplify.
