### ISSUE TITLE
Asynchronous downloads

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1201]
During the download of many files, a significant time is spent waiting for the response of a server in the initial negotiation of the download. We could download in parallel using a thread. Something as simple as a joblib loop with the threading backend and something like 4 jobs would probably be enough to gain a lot.

**Comment by AlexandreAbraham** [comment]
I see several challenges here.

First, error handling. When one gives files to download to the fetcher, it downloads them in a temp dir, it extracts them if needed and run safety check operations. If an error occurs during download (missing file...) the temp dir is deleted and fetching aborted. If it is a success, the content of the temp dir is moved to the dataset dir.
This behavior is a problem because it forced us to segment dataset downloading in small batches. For exemple, when downloading ABIDE (ie hundreds of GB), if somebody happened in the middle of the download, all the downloaded files were erased. That means that it is not as simple as adding an `n_jobs` parameter to `fetch_files`. Second, if parallelized, then we have to stop as soon as an error happens.

Then, there is also a logging issue. The most logical option would probably be to monitor the size of the files from outside of the threads. We'll have to see how to do it.

**Comment by bthirion** [comment]
Stalled. Closing.
