### ISSUE TITLE
reorder dosenbach ROIs in csv or in examples ?

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1206]
I have a version of dosenbach ROIs reoredered. It shows nice connectivity blocks.
![dosenbach](https://cloud.githubusercontent.com/assets/7080143/17456206/0c8cb5d4-5bd0-11e6-93c5-14e6603164b6.png) vs 
![dosenbach_ordered](https://cloud.githubusercontent.com/assets/7080143/17456212/18c4b1f8-5bd0-11e6-9df8-8d2da5e08b15.png)

I don't know if it is better to change the ROIs order in the csv file or reorder them in examples.

**Comment by GaelVaroquaux** [comment]
> I have a version of dosenbach ROIs reoredered. It shows nice connectivity
> blocks.

I'd rather reorder them in them CSV.

However, I think that changing this silently is a bit dangerous.

We could add an option to the loader, and warn that in 1 release the
default will change and the non reordered version will disappear.

That said, I don't find the reordered matrix much more structured. If you
add more subjects/data does it become more structured?

**Comment by AlexandreAbraham** [comment]
> I'd rather reorder them in them CSV.

I am -1 on this for several reasons:

* Several people rely on the numbering of the regions to identify them. If they are mixed up without them knowing, they may make a mistake.
* I don't know where this reordering comes from, but if another one pops up, we may have to chose one.
* If we offer the ability to get the original and reordered versions, the maskers will not be aware of that and they will compute everything for each version.

Since this is a plotting feature, I would be in favor of adding an index in the bunch and let the user reorder things if he wants to do it. An even better option would be to have a function that automatically reorders columns in a connectivity matrix to exhibit structure.

**Comment by salma1601** [comment]
>  I would be in favor of adding an index in the bunch and let the user reorder things if he wants to do it

I also prefer this way

> If you add more subjects/data does it become more structured?

Generally speaking, dosenbach connectivity matrices are well structured. The first matrix does not even respect the networks
