### ISSUE TITLE
Glass brain "lyrz" display mode has switched L and R saggital cuts

### ISSUE THREAD

**Issue by polosecki** [nilearn/nilearn#1258]
Hi,
I noticed that the plot_glass_brain function has swapped L and R saggital cuts: it shows data from the right hemisphere on the saggital cut that is displayed on the left side of the image, and data from left hemisphere on the saggital cut shown on the right side of the image. This can be observed even in the examples from the nilearn online documentation (http://nilearn.github.io/auto_examples/01_plotting/plot_demo_glass_brain.html#sphx-glr-auto-examples-01-plotting-plot-demo-glass-brain-py). 
This is likely a bug, isn't it?
This is the example in the online documentation:
![screen shot 2016-09-01 at 4 08 33 pm](https://cloud.githubusercontent.com/assets/11893584/18182598/a8b4d390-705e-11e6-8aa1-fc4365a6f840.png)

**Comment by MartinPerez** [comment]
This was already fixed by #1183. The online documentation is a bit outdated since the fix is recent.

Here is the same example correctly generated by circleci in a recent pull request.
https://2018-1235740-gh.circle-artifacts.com/0//home/ubuntu/nilearn/doc/_build/html/auto_examples/01_plotting/plot_demo_glass_brain.html

**Comment by polosecki** [comment]
I see, that's great to hear thanks!
