### ISSUE TITLE
transform() of NiftMasker family does not seem ready for big-data

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1415]
I am using nilearn 0.2.5 and tried to apply a conventional grey matter mask on ~500 VBM images from the HCP dataset. Unfortunately, the NiftiMaskers still do not seem to scale to this size of datasets. Running the following line (vbm_files containing paths to the structural images from the HCP500 release) did not finish on my MacBook Pro with 16GB working memory after 3 hours (no other Python or other big processes running at the same time):

``` python
%timeit -n1 -r1 FS = masker.transform(vbm_files)
```

Perhaps an internal batching approach could be thinkable. When I perform the transform() in chunks of say 50 images the transforming operation is rather fast. The big inconvience however is that the confound removal option of the nifti maskers cannot be easily deployed in this way.

Any ideas?

**Comment by mrahim** [comment]
Already said in #1281

**Comment by KamalakerDadi** [comment]
Have you tried MultiNiftiMasker ? It can be scalable in your big size case.

**Comment by AlexandreAbraham** [comment]
To complete Kamalaker's answer: if you use NiftiMasker, data will be concatenated and masked, precisely to be able to run confound removal. The concatenation of your 500 VBM images takes time and memory. With the MultiNiftiMasker, your input will be treated as a list so the images will be loaded one by one.

What worries me is that somebody that has been around nilearn's dev team does not know that. That means that our external users may do the same mistake. Is there a reasonable way to warn users when the input seems fishy in the NiftiMasker?

**Comment by bthirion** [comment]
If I'm not mistaken only one example uses it. This is not enough.

**Comment by banilo** [comment]
I tried again with the ```MultiNiftiMasker```. It also took >1 hour to transform 500 VBM images.

Plus, gathering the whole data internally to be able to run confound removal is by itself not in conflict with internally using a loop over batches. This may prevent memory peaks and the batches can still be concatenated for ```signal.clean()```.

**Comment by MartinPerez** [comment]
I will join this discussion because its relevant to Nistats. I was wondering why the masker was consuming so much memory when processing all runs. Actually for a moment @bthirion was using MultiNiftiMasker in some parts instead of NiftiMasker. This different way to handle memory did not come up in our discussion when deciding the default masker to use everywhere. In Nistats we do not really use any confound removal, so its better to avoid the concatenation, I also think this is not clear from the documentation.

**Comment by GaelVaroquaux** [comment]
> I tried again with the MultiNiftiMasker. It also took >1 hour to transform 500 VBM images.

Are you sure that you are not resampling? For instance by specifying a
mask that is on a different grid than the the data. If that's the case,
it's not surprising that it is taking time. Resampling is a costly
operation. If that's not the case, than please profile the run, so that
we understand what's going on, for instance using "%run -p".

**Comment by banilo** [comment]
> Are you sure that you are not resampling?

As I said above ("When I perform the transform() in chunks of say 50 images the transforming operation is rather fast."), it is considerably faster if I do the same transform() on the same images in batches. As such, the explanation based on a costly resampling procedure is not likely.

**Comment by GaelVaroquaux** [comment]
> As such, the explanation based on a costly resampling procedure is not likely.

Then profile.

**Comment by GaelVaroquaux** [comment]
I am closing this issue: it's not helpful. It's a general comment, and not something that someone (eg an external person to the project) can tackle.
