### ISSUE TITLE
General comments on the documentation

### ISSUE THREAD

**Issue by SylvainLan** [nilearn/nilearn#1426]
Under the supervision from Bertrand Thirion, I have read the documentation of nilearn and may express some comments. 

**General comments** : 
-Even though people tend not to read a documentation sequentially, the sections 4 (plotting) and 5 (manipulating brain volumes) could be put in position 2 and 3. I think it is more convenient to handle statistical tools when one knows and understands the concept of masks. 

-The code in the documentation is often not straightforward and it could be a plus if one could just copy and paste the lines on an iPython terminal to run it. 

-Some parts are redundant and there are explanations of the same subject which come many times in the doc (eg the construction and the inverse of a masker)

**Some warnings**
The code is highly dependent to the sklearn library, and some deprecation warnings appear for : 
-the cross-validation
-other deprecation warning concerning matplotlib (axisbg has to be changed to facecolor)

**Minor requests**
Here are some subjectives remarks on the content of the documentation. In parenthesis is the related part of the documentation : 
-(3.3.1.3) Isn't it possible to order the components to the best independent to the least? 
-(3.3.2) The dictionary learning could be explained a bit 
-(3.4) This section seems redundant with the two previous ones (3.3 and 3.2) and could be merged
-(4.2) The slice selection is not clear when automatic
-(6) This section is a recap of all the previous ones and does not add a lot, but may be volunteer.

**Comment by KamalakerDadi** [comment]
>Some warnings
>The code is highly dependent to the sklearn library, and some deprecation warnings appear for :
>-the cross-validation

As far as I have followed, these warnings are fixed with this PRs #1291 and #1342 in master.

>-other deprecation warning concerning matplotlib (axisbg has to be changed to facecolor)

Fixed with this PR #1395 and one PR #1423 under review. 

Are you able to still see these warnings despite of these fixes ?

>General comments :
>-Even though people tend not to read a documentation sequentially, the sections 4 (plotting) and 5 >(manipulating brain volumes) could be put in position 2 and 3. I think it is more convenient to handle >statistical tools when one knows and understands the concept of masks.

I agree with concept of masks. But, then leads to further discussion and approvals from other people before refactoring.

>-The code in the documentation is often not straightforward and it could be a plus if one could just copy >and paste the lines on an iPython terminal to run it.

If you have observed, we point the link to the example in each section so users can play with the example in IPython.

>-Some parts are redundant and there are explanations of the same subject which come many times in the >doc (eg the construction and the inverse of a masker)

Not so clear. May be you can point to the section.

>Minor requests
>-(3.4) This section seems redundant with the two previous ones (3.3 and 3.2) and could be merged

Merging things can make complex to understand for the users showing everything in one complete section. That's why we made into two parts. Region extraction is a post-processing method when someone wants to split networks into regions. I feel it is in good position in terms of ordering of the section.

**Comment by bthirion** [comment]
Much of it has been addressed.
