### ISSUE TITLE
Avoid resampling when it's just different FOV, and not different affine

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1551]
For two images that are looking at the same data, but with a different FOV, nilearn.image.resample_img currently uses the affine resampling straegy. However, the transformation could easily be done via a simple padding of arrays.

We should probably be able to detect this with the "A" matrix on line 
https://github.com/nilearn/nilearn/blob/e442a34a9eda52b2c2697c5b176ec3d95a99e8d3/nilearn/image/resampling.py#L488
which should pretty much be the identity. Once we've detected this, the challenge will be write code that computes the translation and padding.

The benefit might be a large speedup in some settings, as often the mask and the data are on the same grid (typically the grid of the MNI template at a given resolution), but with a different FOV that was inherited from where they originated.

**Comment by bthirion** [comment]
+1
Actually, when there is only a translation/padding the A matrix should be the identity.

**Comment by GaelVaroquaux** [comment]
Yes, this is what I meant. Sorry, I've corrected.

**Comment by cancan101** [comment]
Is this the same "issue" as calling `nilearn.image.crop_img` and then taking the resulting image affine and passing it to `nilearn.image.resample_img`? e.g I call crop on the image data and then want to apply that same crop to the mask but want to just use array slice-ing rather than a more expensive resample operation?

**Comment by bthirion** [comment]
Indeed.  But the resampling code should detect and handle such situations.

**Comment by YSanchezAraujo** [comment]
anyone know if a PR for this has already been put forth?

**Comment by GaelVaroquaux** [comment]
> anyone know if a PR for this has already been put forth?

I don't think so.

**Comment by KamalakerDadi** [comment]
>anyone know if a PR for this has already been put forth?

Nobody AFAIK. May be @cancan101 ?

**Comment by gkiar** [comment]
Hey everyone! At the Nilearn sprint now and think @GaelVaroquaux and I have a pretty simple plan for taking care of this, in pseudocode below. Let me know if I'm missing a corner case, if I have some flaw in logic, or if you have a better idea? Thanks!

```
if A != I OR (A == I AND not all(b == integers):
  ... normal behaviour (done)
elif A == I AND |b| == 0:
  ... normal behaviour, which happens do be do nothing (done)
elif (A == I OR some combination of permutation(I) and sign-flipped(I)) AND all(b == integers):
  ... special case: can be solved with padding alone
  crop source image and keep track of N voxels offset before/after volume
  flip along sign-flipped dimensions
  shuffle the permuted dimensions
  for each dimension:
    Save index as translation + offset (if not flipped: offset before, else: offset after)
  Insert cropped image into zero matrix at set indices
```

To do this, I'd need to:
1. Add a flag to `crop_img` that toggles also returning the indices of where the cropped volume should be re-inserted into a zeros matrix to recover the original image
2. Add an if statement around https://github.com/nilearn/nilearn/blob/5808d9662cbe1266396d08656a6dc9ac1dca8383/nilearn/image/resampling.py#L539-L543 to catch this special case, compute these indices, and insert the data directly rather than resample. I suspect this will speed up computation time quite a bit, especially in 4D volumes.

I'll tackle the simpler `A == I` case first, and then will build in the permutation/sign flipped ones after.

**Comment by thomasbazeille** [comment]
Solved by #2025, can be closed

**Comment by jeromedockes** [comment]
let's keep it open for now in case we end up reverting #2025

**Comment by bthirion** [comment]
Closing now.
