### ISSUE TITLE
Add function for creating "carpet plots"

### ISSUE THREAD

**Issue by chrisgorgo** [nilearn/nilearn#1585]
![image](https://user-images.githubusercontent.com/238759/34458010-db79fd22-ed77-11e7-844b-7af9b6c01c48.png)

Potentially ported from MRIQC (see https://github.com/poldracklab/mriqc/issues/674)

**Comment by bthirion** [comment]
Thx for the suggestion.
* In the plot, you suggest to rely on a voxel-based representation, but for large number of voxels (10^4-10^6) this will not render nicely visually. Do you implicitly suggest to rely on some super-voxel representation ?
* what does the colorbar on left side mean ?

**Comment by chrisfilo** [comment]
The Y axis is mislabeled. It should say "parcells" or "regions" since voxels are averaged to reduce dimensionality. The colorbar indicates different parcells and their class (cortical, subcortical, CSF). The legend could be improved. More resources:
- original paper describing this visualization: http://sci-hub.tw/10.1016/j.neuroimage.2016.08.009
- accompanying videos and MATLAB code: https://www.jonathanpower.net/2017-ni-the-plot.html

For nilearn I was thinking about the following function signature:

`plot_carpet(img, parcellation_img)`

where `img` will have to be and the `parcellation_img` needs to be in the same space as `img`. WDYT?

**Comment by bthirion** [comment]
Sounds reasonable to me. Additionally 'parcellation_img' would be optional. Additionally,
'False' would mean no reduction, and an int value (k) would compute a parcellation to k supervoxels  on-the-fly .
PR welcome !

**Comment by chrisfilo** [comment]
I'm planning to send a PR.

What parcellation should be used if none is provided?

**Comment by bthirion** [comment]
You can simply rely on Ward clustering (with e.g. n_regions=1000).

**Comment by chrisfilo** [comment]
I was actually incorrect. Each line of the plot corresponds to one voxel (within EPI mask). The segmentation/parcellation is only used to distinguish cortical and subcortical voxels. Ward parcellation cannot help with that, but it's questionable how useful that subdivision is.

**Comment by bthirion** [comment]
relying on some type of supervoxels is useful for readability of these carpet plots imho. The distinction btw cortical and subcortical is not relevant for this.

**Comment by chrisfilo** [comment]
Yup - I just sent a PR with basic implementation that uses imshow to implicitly average groups of voxels (via auto scaling). This is consistent with the original implementation, but another PR could add optional Ward clustering.

**Comment by GaelVaroquaux** [comment]
Sorry, I am coming late to the discussion, but it seems to me that the
function signature should be to take time-series, and not an 4D niimg.
The reason that the function with the 4D niimg is a bit too specific (as
illustrated by the discussion above), while the function with time-series
is applicable in several places and with several purposes.

For instance, I would add it at the end of the example
http://nilearn.github.io/auto_examples/03_connectivity/plot_signal_extraction.html
to show that difference between with and without confound removal. This
would be good also to fullfill our rule that no user-exposed function
should be added without being integrated to an example.

**Comment by chrisfilo** [comment]
Taking 4D niimg as an input was driven by a user case and thus I think it is useful (it does not require user to extract signals if they have not done it earlier). 

What about signature that takes time-series or niimg?

**Comment by GaelVaroquaux** [comment]
It's actually not completely clear to me what is the expect usage on a raw 4D nifti file. With ~50 000 voxels in a typical brain, the visualization will be overcrowded and unusable.

In nilearn, we tend to like to use every function that we add in an example, to ensure that the purpose is well understood and to guide the design. Maybe this would help me. I had seen an usecase and a corresponding example, that I mention above, but it required signal extraction.

Also, I am not terribly enthousiastic about a signature so versatile that it works both on 4D niimgs, and time-series. It's not something that we've done in nilearn, to have clear user design and enable good error management.

**Comment by chrisfilo** [comment]
On Sun, Jan 14, 2018 at 1:12 PM, Gael Varoquaux <notifications@github.com>
wrote:

> It's actually not completely clear to me what is the expect usage on a raw
> 4D nifti file. With ~50 000 voxels in a typical brain, the visualization
> will be overcrowded and unusable.
>
It's still very usable - basically imshow does implicit scaling so it's not
overcrowded. AFAIK this is how the original implementation worked and how
similar plots have been used in MRIQC. See my PR and the first post of this
issue for examples.

> In nilearn, we tend to like to use every function that we add in an
> example, to ensure that the purpose is well understood and to guide the
> design. Maybe this would help me. I had seen an usecase and a corresponding
> example, that I mention above, but it required signal extraction.
>
I'll add an example when I find a moment.

> Also, I am not terribly enthousiastic about a signature so versatile that
> it works both on 4D niimgs, and time-series. It's not something that we've
> done in nilearn, to have clear user design and enable good error management.
>
I'm just implementing what is a use case I saw. We can have two functions
to keep the API clean. I think that having a function that takes a 4D epi
file and plots a carpet plot (optionally doing ward clustering internally)
would be very useful.

**Comment by bthirion** [comment]
Having two functions sounds good indeed.

**Comment by oesteban** [comment]
I've been working lately on this (still in mriqc/niworkflows/fmriprep proper) and I think I can take it from here @chrisfilo. I will continue the works on #1587.

Regarding the different issues we've touched on so far (in no particular order):

- **Having 2 functions / a single catch-all function / a single ndarray-based function**. I would lean towards having a single ndarray function. The only reason for using niimgs is accessing the TR, we could add that as an argument and use #TRs as units if it is `None`. We probably want to have an additional wrapping function for niimgs in one use case I'll comment below.

- **Documentation: example**: I'm all in with this. Also you provided some pointers to interesting datasets, so I will add it.

- **Tests**: I think I have in mind some tests that may cover this function well enough.

- **Voxel-dimension reduction**: @GaelVaroquaux is right on that it is not possible to plot all timeseries. In MRIQC we were using the implicit decimation that matplotlib applies, and in my latest implementation I made this explicit. Even with this decimation of the voxels axis, the plot is extremely useful. If you can think of a more clever way of reducing that dimensionality without removing relevant time-series I will be more than happy to add it.

- **Clustering**: the interpretability of the plot improves a lot if it is possible to render the timeseries from the cortex at the top and then deep gray matter and cerebellum to finally have white matter and csf in the bottom. Basically, we want to separate signals of interest and no interest in this plot. I keep the idea of the hierarchical clustering for when a segmentation is not provided (knowing that voxels from cortical/subcortical regions will be mixed). In my latest implementation with a segmentation, the user can pass a lookup table to map the labels of the segmentation to the 4 classes I mentioned before. Ward clustering could be used then within each class to extract those "supervoxels".

- **Segmentation**: when a segmentation is provided, it is possible to render on the right hand some axial views (for example) of the segmentation, with colors matching the legend of the carpetplot so it is immediate to understand from where the signals come. For this use-case, it makes sense having access to the niiimg properties.

- **Atlas**: alternatively, this could be done enforcing the input data to be resampled into some atlas space (and use some of the atlases already in nilearn to segment data). However, this plot is very sensitive to resamplings and this use case is only valid for pre-processed data (e.g. if one wants to compare the carpetplot before and after processing, this could be the after).

Both atlas and segmentation would help reduce the number of voxels. Passing a LUT it is possible to exclude whole regions (e.g. the cerebellum). Also, the surviving ROIs could be eroded with another optional argument. Combining both the number of voxels can be possibly reduced from ~50K to ~20K without naive decimation. It is still too much (we want to have ~1K voxels or less).

Finally, this plot could also be useful for diffusion data. In that case, I would use the hierarchical clustering to reorder the 4th axis, so that close diffusion orientations are plotted together.

**Comment by GaelVaroquaux** [comment]
Hey Oscar,

Thanks a lot for this summary. I think that all the points that you list
are excellent points, and I am really looking forward to it. I'll try to
make sure that we review this PR fast, and merge it soon!

**Comment by bthirion** [comment]
Thx !

**Comment by tsalo** [comment]
Since #1587 is labeled as stalled, would it be alright for me to pursue this? I can pull from the existing PR to start working from where it stalled, or I can start from scratch.

**Comment by thomasbazeille** [comment]
Sorry about the "Stalled" label @chrisgorgo @oesteban, just a quickly chosen name but would like to thank you for the great work and find a path forward for it not to be lost !

Both proposals of @tsalo seem fine by me !

**Comment by oesteban** [comment]
@tsalo happy to help, thanks for picking up
