### ISSUE TITLE
Bug in plot_connectome when setting both `display_mode='lyrz'` and `node_color`

### ISSUE THREAD

**Issue by tjiagoM** [nilearn/nilearn#1607]
Hi,
I'm using nilearn 0.4.0.

When I run the following code:

```
plotting.plot_connectome(np.array([[0,3], [3,0]]),
                        [[-53.60, -62.80, 36.64], [23.87, 0.31, 69.42]], 
                        node_color='red')
```

I have:
![image](https://user-images.githubusercontent.com/7031523/36355192-cc355f82-14d7-11e8-9bac-fa68421f57b2.png)

However, if I add a custom display mode like this:
```
plotting.plot_connectome(np.array([[0,3], [3,0]]),
                        [[-53.60, -62.80, 36.64], [23.87, 0.31, 69.42]], 
                        display_mode='lyrz',
                        node_color='red')
```

I have a TypeError exception:
![image](https://user-images.githubusercontent.com/7031523/36355218-10b6277c-14d8-11e8-82c0-e4184df0e4a3.png)

**Comment by bthirion** [comment]
As far as I can see, this happens because `marker_color` can be either a string of a list (it is a string on that case, which raises the issue).
I believe that the solution is to test in the function the type of `marker_color`: if it is  a string, then no selection is necessary.
Of course, a test should be added to ensure that the code is correct.
@tjiagoM can  you issue a PR ?

**Comment by tjiagoM** [comment]
@bthirion Ok, I will have a look when I have time and make a PR.

**Comment by KamalakerDadi** [comment]
Closing this one in #1615
