### ISSUE TITLE
resize vs resample

### ISSUE THREAD

**Issue by samieti02** [nilearn/nilearn#1692]
hello dear sir,
i have a question reagarding resizing the image. I have used the function resample_img and add a target shape of 200x200x200 but the image has been cropped/clipped, although I set clip=False;

![v1_1_nilearn](https://user-images.githubusercontent.com/23456648/42734464-a63c94d6-8844-11e8-85b7-3c431a383826.PNG)
![v1_2_nilearn](https://user-images.githubusercontent.com/23456648/42734465-a6646a38-8844-11e8-8de4-6f97c04e6e23.PNG)

In v1_1 we have the normal image and in v1_2 we have the clipped image.
How can I resize correctly the image without clipping it with the voxel size that i want and the target_shape ??

The following functions
_img = resample_img(img_3d, target_affine=np.eyes(3), target_shape=(200,200,200), clip=False)  
    OR
_img = resample_img(img_3d, target_affine=np.eyes(3), target_shape=(200,200,200), clip=True)

crop the image, if we have an image with the dimension n=(210, 205, 205) and voxel size (0.8, 0.8, 2).

But how to keep the same dimension of an image for a voxel size of for example (1,1,1) ?

thanks
Sami

**Comment by bthirion** [comment]
well the original image as voxel size 2mm in z direction. you may want to increase  the number of slices in the third dimension; Also, you may want to use a more complex target affine, i.e. with a non-zero translation component --depending on your original affine.

**Comment by samieti02** [comment]
Lets say we have 2 images (x,y,z), z for the slices  with the dimension (30,26,50) and voxel size (0.8, 0.8, 2) and the 2nd (18, 21, 65) with voxel size (0.9, 0.9, 3.1) 
And I want to resize and resample them to the size of (25,25,25 ). with voxel size (1,1,1). I will write the following code for example

`_img1_res = resample_img(img1, target_affine=np.eyes(3), target_shape=(25,25,25), clip=False)`
`_img2_res = resample_img(img2, target_affine=np.eyes(3), target_shape=(25,25,25), clip=False)`

The images will have the expected voxel size and image size(target shape), but some parts of the images would be clipped, as I show on the images above.
How can I make that they get not clipped, considered that the image slices are already be given by scanning the patient brain (the number of slices can not be changed)? Or I dont know how you mean that by adding more slices ?

**Comment by zanospi** [comment]
Hi,

I think you are mistaking the clipping mechanism with cropping. The `clip` argument is there to avoid getting voxels with values outside of your initial range of values because of resampling, it does not change the size of the data.

Regarding your cropping isssue, you are trying to resample your data to a smaller volume, so cropping is to be expected. The true volume of your data is given by **affine * shape**: 

* your MRI with a (0.8, 0.8, 2) affine and (30, 26, 50) shape corresponds to a volume of 24mm * 20.8mm * **100mm** in the real world
* if you resample it to (1,1,1)*(25,25,25) it won't fit in the corresponding 25mm * 25mm * **25mm** volume and it has to be cropped
* if you want to resample many MRIs to a common affine+shape without any of them being cropped, you need to ensure that the corresponding dimensions are big enough for any of them to fit. For the example in your 2nd message, you need at least:

  * affine_x * shape_x > 24
  * affine_y * shape_y > 20.8
  * affine_z * shape_z > 201.5 (because of your 2nd MRI which is bigger in the 3rd dimension)

What @bthirion was suggesting was indeed increasing the 3rd dimension (Z-axis = slices) so that both your MRIs fit.

Regards

**Comment by samieti02** [comment]
Hello,

thanks @zanospi  for the good explanation. Now it is clear. @bthirion thanks too.
Is there a way to resize the image? There is the function for resampling but not for resizing?
With resizing, we do not affect directly the voxel size.

Thanks

**Comment by bthirion** [comment]
I'm not aware of such functions: you may want to you `crop_img` but then you don't have control on the resulting shape.
Actually, I don't think that this is possible: you need to define in some way the field of view of the images after resizing. I don't see how to do that ?
Best,
