### ISSUE TITLE
Surface plotting with multiple views (montage plots of stat maps on brain surface)

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1722]
Following the discussion in this PR #1713. This issue is about adding a new function ```plot_surf_stat_montage``` which basically should have an argument called ```display_mode``` to plot brain surface in multiple views.

@jeromedockes @GaelVaroquaux @bthirion please provide more details if somethings are missing.

**Comment by jeromedockes** [comment]
> please provide more details if somethings are missing.

I think that's about it :)
@dangom what interface did you have in mind?

**Comment by dangom** [comment]
Not sure how flexible `plot_surf_stat_montage` should be. Perhaps it's better to keep it simple with few display modes and add examples in the documentation on how to generate more advanced, custom montages.

The interface I had in mind would take as input from the user a 3D volume, and optionally a dictionary with `{'left': pial_left, 'right': pial_right, 'bg_left': sulcus_left, 'bg_right', sulcus_right}`, and do all of the lifting necessary for the plots, i.e., calling `vol_2_surf` & `plot_surf_stat_map` with the correct textures. I say optionally because we could default to fsaverage. The interface would return the `fig, axes` objects to the caller.

What I love about `display_mode` is that it prepares the data such that everything goes into a single `AxesSubplot` object.  It's not so trivial to do the same for the montage because placing objects into a single 3D space and guaranteeing aesthetically pleasing figures is a much harder problem than in 2D. Also, we can't reuse any of the `display_mode` code available for surfaces. =/

I think we all agree `plot_surf_stat_montage` has to use multiple `AxesSubplot` objects because we need multiple cameras.
Now, we could still use the same `display_mode` kwarg in `plot_surf_stat_montage` to refer to which views we want in the montage. I can see `lateral`, for L&R lateral, and `lateral-medial`, for L&R lateral and medial views (as shown in #1713) as possible values. We could start with those and add more from combinations of `{lateral’, ‘medial’, ‘dorsal’, ‘ventral’, ‘anterior’, ‘posterior’}`  per request.

**Comment by jeromedockes** [comment]
sounds great! 

> Perhaps it's better to keep it simple with few display modes and add examples

I agree. the views you showed in #1713 would be a great start

do you think there should be an option to use inflated surfaces? I think users will ask for it

just a couple of details:
- if the user gives a dictionary rather than using one of the provided `'fsaverage5'` (the default) or `'fsaverage'`, I would require it to have the same keys as the ones returned by `fetch_surf_fsaverage`, i.e. 'pial_left', 'pial_right', 'sulc_left', 'sulc_right', and 'infl_left', 'infl_right' if necessary. It will be easier for you because then you can treat all meshes in the same way, and easier for users who won't have to remember another set of names.
- I still think `plot_surf_stat_montage` is too similar to `plot_surf_stat_map`, which accepts a surface map. the name should probably have `on_surf` somewhere in it.

**Comment by jeromedockes** [comment]
> We could start with those and add more from combinations of {lateral’, ‘medial’, ‘dorsal’, ‘ventral’, ‘anterior’, ‘posterior’}

for each of these views you could have a function that generates a row of two axes, for left and right hemispheres, as you did in #1713, and then the user can stack these rows in the order they want by joining the names of the views with '+'

**Comment by dangom** [comment]
Inflated should be an option as well. Definitely! 

I'll try to put together an initial PR still today or tomorrow and we can iterate on that.
