### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1761]
The latest nilearn is an alpha: 0.5.0a. As a result, most users are not getting it.

I would like to release 0.5.0 soon (partly because there is a tutorial this Saturday). Anything urgent that should go in?

**Comment by kchawla-pi** [comment]
Python2 deprecation warning. Would be good if its emphasized during the tutorial as well.

**Comment by jeromedockes** [comment]
> Anything urgent that should go in?

Nothing absolutely necessary IMHO. releasing 0.5.0 will be good because currently the online documentation doesn't match the version pip installs by default

**Comment by kchawla-pi** [comment]
Based onmy experience with Nistats, we should do a thorough install of NiLearn and document it, because there are packages required by NiStats and I would think Nilearn, which are not installed by the current installation procedures. 
The example I remember (there are more) is the boto3 library, required to access openneuro datasets but not installed as part of installing Nistats and I feel certain, Nilearn.
I have been circumventing this issue by installing Nilearn using Conda from the conda-forge channel.

**Comment by jeromedockes** [comment]
boto3 is not used in nilearn. there may be some dependencies that are not correctly listed in the setup; in this case could you pip install nilearn in a fresh environment and report which are missing? note that not all dependencies are required: you can use most of nilearn without matplotlib, but it is required for plotting

**Comment by kchawla-pi** [comment]
> could you pip install nilearn in a fresh environment

It's on my TODO for today.
> boto3 is not used in nilearn

boto3 is used for fetching openneuro datasets. Maybe I am confusing it with nistats, I will check it today.

**Comment by jeromedockes** [comment]
> boto3 is used for fetching openneuro datasets. Maybe I am confusing it with nistats, I will check it today.

yes. it's definitely not used in nilearn

**Comment by kchawla-pi** [comment]
Checkout #1762
