### ISSUE TITLE
Add fetch_HCP()

### ISSUE THREAD

**Issue by QinglinDong** [nilearn/nilearn#1824]
Is it possible that we add Human Connectome Project to automatic dataset fetching?

**Comment by bthirion** [comment]
Hi,
The HCP dataset represents terabytes of data and is actually quite complex... I'm not sure that we can reasonably handle than in the framework on Nilearn. What data do you have in mind ?
Note that we recently uploaded HCP900 activation maps on Neurovault (https://neurovault.org/collections/4337/), which can be fetched through Nilearn.

**Comment by GaelVaroquaux** [comment]
> Is it possible that we add Human Connectome Project to automatic dataset fetching?

I think that this is out of scope: the goal of the downloaders are to
write examples and to teach, rather than to be a library of downloads: it
would be too much to maintain (the downloaders are actually quite
annoying to maintain, as we don't control the Internet).

One way around these problems would be to have a somewhat generic
downloader from openneuro. But is HCP on openneuro? Also, it just seems
to me that the download is orders of magnitude too big. The most
efficient way of getting the HCP is to order the drives.

**Comment by KamalakerDadi** [comment]
>But is HCP on openneuro? 

The contrast maps atleast are on

**Comment by KamalakerDadi** [comment]
>But is HCP on openneuro?

>The contrast maps atleast are on

Sorry do you mean neurovault ?

**Comment by bthirion** [comment]
No HCP is not on OpenNeuro.

Downloading time series (task or resting-state) is  not an option due data size (about 200G IIRC) and download time.
the only thing that we can reasonably afford is to download beta maps from NeuroVault (#4337).

**Comment by GaelVaroquaux** [comment]
On Thu, Oct 18, 2018 at 01:39:02PM -0700, KamalakerDadi wrote:
> >But is HCP on openneuro?

>     The contrast maps atleast are on

> Sorry do you mean neurovault ?

No, I meant openneuro.

**Comment by GaelVaroquaux** [comment]
> the only thing that we can reasonably afford is to download beta maps from
> NeuroVault (#4337).

OK, but then we already have the functionality. We should just add a
comment here and there (eg in the docstring of the neurovault downloader)
on how to download them.
