### ISSUE TITLE
Bug of resample_to_img

### ISSUE THREAD

**Issue by QinglinDong** [nilearn/nilearn#1825]
Plotting volume from adhd is good, but plot after resampling to template is a mess. Here is the code:

`from nilearn import datasets
from nilearn.image import load_img
adhd_dataset = datasets.fetch_adhd(n_subjects=1)
func_filenames = adhd_dataset.func  # list of 4D nifti files for each subject
raw=load_img(func_filenames)

from nilearn.datasets import load_mni152_template
template = load_mni152_template()
template_img = load_img(template)

from nilearn.image import resample_to_img
resampled_stat_img = resample_to_img(raw, template)

from nilearn.image import iter_img
from nilearn.plotting import plot_stat_map, show
for i, cur_img in enumerate(iter_img(resampled_stat_img)):
    plot_stat_map(cur_img, display_mode="z", title="IC %d" % i,
                  cut_coords=1, colorbar=False)
    show()
`

**Comment by GaelVaroquaux** [comment]
I tried out the code that you posted, and it does give a plot that seems
a bit surprising. However, it's surprising just because it is an unusual
cut of the brain. Ie: it's just a bad visualization, and nothing is
wrong. Try to following to have a better visualization:

<pre>
plot_stat_map(cur_img, display_mode="ortho", title="IC %d" % i,
              colorbar=False, black_bg=True)
</pre>

**Comment by QinglinDong** [comment]
Thank you so much for the fast reply! @GaelVaroquaux
