### ISSUE TITLE
Add versionadded sphinx directive in documentation

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1865]

**Comment by tsalo** [comment]
Is this still something we plan to do? I ask because I'm reviewing #3065 and it might make sense to include `versionchanged` directives to the docstrings in the new `maskers` module.

**Comment by jeromedockes** [comment]
I think it's very useful so I vote we do it! adding it to existing code sounds like a lot of tedious work but we can do it progressively, and at least start including these directives for new changes

**Comment by NicolasGensollen** [comment]
Also +1 on this.
I'm trying to ask it systematically for new things. Adding it to existing code is indeed a lot of work, but it would be a nice addition.

**Comment by tsalo** [comment]
Given that we have been using these directives pretty consistently in recent PRs, I think we can simply add a line about including versionadded and versionchanged directives to the contributing documentation.

Should we agree on a convention for adding these directives though? As PRs are merged in, contributors may not know the next version that will be released (i.e., whether it will be a patch or minor release), so we could hypothetically accrue incorrect directives between releases, unless we make updating/checking the directives part of the release process. This would probably be easiest if we stuck with the current `.dev` version in the directives, so that the releaser could easily search and replace across the whole package.

**Comment by bthirion** [comment]
Excellent point.
Yes, we have then to be explicit about that in the release process description.
