### ISSUE TITLE
Switch to PEP8 style absolute imports

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1919]
We should change the relative imports used in NIlearn to PEP8 endorsed absolute imports.
 Relative imports misbehave/break more and are less clear to read.
Relative imports tend to break more for reasons that are not readily apparent, especially within IDEs.

I know relative absolute imports are acceptable alternatives according to PEP8, but the ones in Nilearn and Nistats often break for me when I want to run specialized tools and test runners from within the IDE instead of the terminal.

**Comment by jeromedockes** [comment]
from https://www.python.org/dev/peps/pep-0008/#id23 : 

  Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path):
```
  import mypkg.sibling
  from mypkg import sibling
  from mypkg.sibling import example
```

**Comment by GaelVaroquaux** [comment]
Over my 15 years of doing Python, PEP8 has changed its recommendations
quite a few times (I do believe that relative imports where recommended a
few years ago).

I've always considered massively changes to code bases due to changes in
PEP8 recommendations bad practice. They are not only a loss of time, but
also tend to create conflicts in open pull requests.

And if a recommendation is so arbitrary that it changes over time, I
think that it can be seen as a rounding error.

My opinion is not that absolute imports are better, because relative
imports make refactoring easier.

However, if the consensus is that absolute imports are better, I am fine
changing nilearn's policy and encouraging new code to have relative
imports. I do frown on a massive change to the code base.

**Comment by jeromedockes** [comment]
> I've always considered massively changes to code bases due to changes in PEP8 recommendations bad practice. They are not only a loss of time, but also tend to create conflicts in open pull requests.

+1 !
