### ISSUE TITLE
_threshold_maps_ratio changes the input map

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1933]
My maps images keep changing when I use RegionExtractor. I think we need to make a copy [here](https://github.com/nilearn/nilearn/blob/master/nilearn/regions/region_extractor.py#L58)
For instance the following code throws an `AssertionError: Arrays are not equal`
```Python
from nilearn._utils.data_gen import generate_maps
import numpy as np
from nilearn.regions.region_extractor import _threshold_maps_ratio

maps, mask_img = generate_maps((10, 10, 10), 30)
maps.get_data()[:5] = 100
maps_data = maps.get_data().copy()
thresholded_maps = _threshold_maps_ratio(maps, threshold=1)
np.testing.assert_array_equal(maps.get_data(), maps_data)

```

**Comment by bthirion** [comment]
are you including this in your PR ?

**Comment by salma1601** [comment]
No. It is preferable to do a separate PR no ?

**Comment by bthirion** [comment]
indeed.BEnvoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : salma1601 <notifications@github.com> Date : 01/03/2019  08:51  (GMT+01:00) À : nilearn/nilearn <nilearn@noreply.github.com> Cc : bthirion <bertrand.thirion@inria.fr>, Comment <comment@noreply.github.com> Objet : Re: [nilearn/nilearn] _threshold_maps_ratio changes the input map (#1933) No. It is preferable to do a separate PR no ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nilearn/nilearn","title":"nilearn/nilearn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nilearn/nilearn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@salma1601 in #1933: No. It is preferable to do a separate PR no ?"}],"action":{"name":"View Issue","url":"https://github.com/nilearn/nilearn/issues/1933#issuecomment-468575807"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nilearn/nilearn/issues/1933#issuecomment-468575807",
"url": "https://github.com/nilearn/nilearn/issues/1933#issuecomment-468575807",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
