### ISSUE TITLE
Plans to add surface-based SpaceNet functionality?

### ISSUE THREAD

**Issue by adkinsty** [nilearn/nilearn#2132]
I would like to run the SpaceNetClassifier on images in surface-space. There are many advantages to using surface-space instead of volumetric space. So, it would be useful to be able to run the analysis on surface-space data. Are there any plans to make the SpaceNet compatible with surface-space data?

**Comment by bthirion** [comment]
Good question !
Indeed, it certainly makes sense to implement a SurfaceSpaceNet.
Yet, there are no current plans to do it: 
* You maybe the first person who requested it, while the volume version has been around for 5 years or so.
* The optimization to make it work is a bit hairy, so that the adaptation to the surface needs a bit of effort (implementation, documentation, testing, demontrsation in examples).
* Maybe more importantly, We have realized that the FREM approach is better in terms of compromise between accuracy, computation time and stability (Hoyos Idrobo et al. nimg 2017); hence, if we had found time to dedicate to this, we would start by implement FREM  on the cortical surface.
* But someone has to find time for that ;-)

**Comment by adkinsty** [comment]
Thanks for the quick reply! I especially appreciate you mentioning FREM. I had never heard of this before. I recently started using SpaceNet over SearchLight but I guess I may need to familiarize myself with FREM. 

And no worries about implementing surface-space functionality. I was just curious. I'm grateful for the work that you all do to make these sorts of analyses easy to run for researchers like me.

**Comment by bthirion** [comment]
Yes, I'd rather invest time in implementing FREM on the surface. It should be easier yet give as good or better results.

**Comment by Remi-Gau** [comment]
ok so I am closing this one for now
