### ISSUE TITLE
NiftiLabelsMasker misbehaves for integer niftis

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#2135]
For niftis like the example attached to this issue, NiftiLabelsMasker() from the masker family does not seem to carry out expected behavhior. Using this nifti as argument for labels_img leads .transform() to produce only zero outputs. The reason appears to be that the internal mean() operation on the voxels of each atlas region may not work properly if the data nifti is integer typed. In the case of 0/1 integer values, this leads to <1 values in many atlas regions, and thus to only zeros in the transformed variable outputs.

[some_one_zero_nifti.gz](https://github.com/nilearn/nilearn/files/3628442/some_one_zero_nifti.gz)

**Comment by jeromedockes** [comment]
thanks @banilo !

this is the problem:

https://github.com/nilearn/nilearn/blob/a2c33401793a09cc1b9b0ae97e02a08b297c503d/nilearn/regions/signal_extraction.py#L105

**Comment by jeromedockes** [comment]
to clarify, the problem is not related to the image you provided, but to masking
images of integer types. the mean computed in each region is cast to the same
integer type. but then the image returned by the masker is of floating-point
type, leaving the user wondering why the means are truncated to their integral
part
nilearn should either work only with floating-point, or return an image of the
same type as the input.

**Comment by kchawla-pi** [comment]
I will take a crack at fixing this. Would ceiling a decimal value to 1 have the desirable effect?

**Comment by jeromedockes** [comment]
> I will take a crack at fixing this. Would ceiling a decimal value to 1 have the desirable effect?

no, what you need to do is store the computed signals in np.float64
instead of the input dtype (at the line that I linked above)

**Comment by banilo** [comment]
in any event, it is a bug. Bugs should be fixed one way or the other.
