### ISSUE TITLE
Better Developer docs

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2142]
Currently our documentation does not cater well to developers. Emdupre contributed a getting started guide for external contributors, which is a good start but we should do more.

We do not have a central location where devs can go and read up on:
1. Developer relevant API changes: As we all know, it is tremendously helpful that Pandas, Scikit-Learn document non-public API changes when we are adapting code to work with new versions of these libraries, so this is a problem. Maybe Nilearn is not used as a tool the same way these libraries are used yet, but it may very well be in future and we should start piecemeal improvements on this front now.
2. Development related utilities: Utilities that are helpful for development that we include in the code. Currently it is dependent on one of us guiding new contributors, incl. new additions to the team. This is not a good long-term solution, and a sticking point in making Nilearn self-sustaining.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux vis-a-vis our email exchange, this is one of the issues for better dev docs.

**Comment by kchawla-pi** [comment]
Examples of dev friendly functions which won't be discovered by external devs unless pointed out by one of us:
The `replace_parameters` decorator.
The separate requirements files for developing and building docs.
The many mocking functions we use in testing.

**Comment by emdupre** [comment]
Thanks for starting this conversation, @kchawla-pi !

As @GaelVaroquaux was on-boarding new developers to the repo this morning, I took a few notes on resources that might be useful:

- The [Sphinx RST guide](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)
- Why we prefer that you [open an issue before a pull request](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/)

**Comment by GaelVaroquaux** [comment]
>   • The Sphinx RST guide
>   • Why we prefer that you open an issue before a pull request

Pointers to the sphinx-gallery docs.

**Comment by thomasbazeille** [comment]
I think this is still a conversation to have. 

We heavily miss general guidelines to make our expectations clear for people that want to open a PR, such as:
- for bugfix we want a new test that fails with current master and is fixed by the PR 
- for new features we want tests, and including it in the documentation and what's new
- tests should be seeded (with a standardized object) and not use datafetchers
- if a feature is coming with new API we should discuss it in a issue ahead 
- a few better details on debugging documentation problems and so on (see [this PRs comments](https://github.com/nilearn/nilearn/pull/2476#issuecomment-697333591)

We could also try to smooth the contribution process, although I'm not sure so much can be made through the docs(#2531)

We could finally reuse some material of our conference on scientific software development for more in depth dev philosophy.

**Comment by bthirion** [comment]
I fully agree.
Yet, I find it striking how non-specific (to Nilearn) most of these points are. I'm wondering whether these are not repeated in many places ? I have the feeling that people better adopt these informal rules when they realize that they are not the result of some whim.

**Comment by jeromedockes** [comment]
A lot of this stuff is covered in scikit-learn's [contributing guide](https://scikit-learn.org/stable/developers/contributing.html), maybe we can point to it or copy part of it to this repo? Re. git tips the git documentation is pretty perfect so I'm not sure what we could add

**Comment by thomasbazeille** [comment]
> Yet, I find it striking how non-specific (to Nilearn) most of these points are. I'm wondering whether these are not repeated in many places ? 

Maybe I didn't motivate this claim enough. All of this is aimed at smoothing the reviewing process and the resulting frustration for contributors and time spent reviewing for core devs'. One big part of reviewing comments is about not respecting our conventions. If they were clear in advance this would lighten the burden for everyone (e.g: how many PRs did recently go through one more round of answers because of a missing "what's new" entry, which even us sometimes forget). 
Two reasons I can think of:

- docs are not good enough (and rules are not so well defined)
- everyone contributing may not be familiar or have read recently Nilearn's contributing doc, let alone scikit one's.

> A lot of this stuff is covered in scikit-learn's [contributing guide](https://scikit-learn.org/stable/developers/contributing.html), maybe we can point to it or copy part of it to this repo? 

We already point to the scikit-learn's contribution guide. Which is very detailed and long, covers many case, it's hard to know how this is related to nilearn. I think we should repeat the main points concerning nilearn (in a concise way, maybe a checklist ?)  And link to other's work for more in depth.

Then how to enforce them, maybe an automatic comment when a PR is open ?



One other problem is that people that contribute . Maybe an automatic pointer to them when a PR is open ?

**Comment by jeromedockes** [comment]
>  (e.g: how many PRs did recently go through one more round of answers because of a missing "what's new" entry, which even us sometimes forget). 

I forget it all the time :) 


> We already point to the scikit-learn's contribution guide. Which is very detailed and long, covers many case, it's hard to know how this is related to nilearn. I think we should repeat the main points concerning nilearn (in a concise way, maybe a checklist ?)  And link to other's work for more in depth.
>

I think a checklist is a good idea, you're right that the guidelines are
a long and detailed page people won't read them

> Then how to enforce them, maybe an automatic comment when a PR is open ?
>

We could add it; I'm not sure if people actually read these comments

**Comment by jeromedockes** [comment]
>>  (e.g: how many PRs did recently go through one more round of answers because of a missing "what's new" entry, which even us sometimes forget). 
>
> I forget it all the time :) 
>

And I also forget to check it when I review a PR .
for that particular example maybe the CI could at least check that
whatsnew has been modified. although there are quite a few PRs that
don't require a whatsnew entry

**Comment by thomasbazeille** [comment]
> > (e.g: how many PRs did recently go through one more round of answers because of a missing "what's new" entry, which even us sometimes forget). I forget it all the time :)
> And I also forget to check it when I review a PR . for that particular example maybe the CI could at least check that whatsnew has been modified. although there are quite a few PRs that don't require a whatsnew entry

Not sure this can be automatized so much. Maybe some quick reviewing checklist or guidelines could be added as well in the docs. The [scikit guidelines](https://scikit-learn.org/stable/developers/contributing.html#code-review-guidelines) are a bit complex for us but a minimal version of that could be working. I also love the [PRs saved replies](https://scikit-learn.org/stable/developers/tips.html#saved-replies).

**Comment by thomasbazeille** [comment]
Does anyone has a clear idea on why we have a page /doc/development.rst  quoting directly /CONTRIBUTING.rst?

**Comment by jeromedockes** [comment]
> Does anyone has a clear idea on why we have a page /doc/development.rst  quoting directly /CONTRIBUTING.rst? 
nope

**Comment by bthirion** [comment]
+1

**Comment by GaelVaroquaux** [comment]
To avoid duplication (two pages are harder to maintain than 1).

CONTRIBUTING.rst is for github to pick.

The other page is for the website.

**Comment by thomasbazeille** [comment]
> To avoid duplication (two pages are harder to maintain than 1). CONTRIBUTING.rst is for github to pick. The other page is for the website.

Okay ! For now the content is split between both pages with section about the scope of the project and a primer on how to contribute in /doc/development.rst  versus a detailed contribution guide in CONTRIBUTING.rst.

Actually it creates repetition and is hard to refactor. I suggest to put everything we need in CONTRIBUTING.rst and cite it in the website then.

**Comment by bthirion** [comment]
Sounds reasonable.
