### ISSUE TITLE
Mybinder should probably point to tag

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2318]
Currently, launching the binder instance points to master. As a consequence, each time there is a commit in master, mybinder needs to regenerate the images, which takes a while.

I think that we should consider pointing to the latest release via a tag. @emdupre : WDYT?

As a consequence, we should update the release procedure to make sure that this tag is updated.

**Comment by emdupre** [comment]
It's pointing to the `master` branch of the documentation website (nilearn.github.io), so it only needs to re-generate when a new commit is pushed there ! Since we're currently only pushing to that repo when a new release is cut, we're effectively pointing to the most current release tag (of `nilearn/nilearn`), rather than the most current commit.

Did you mean we should consider updating the documentation site s.t. it's also under the same release tags ?

**Comment by GaelVaroquaux** [comment]
Sorry, I missed that it was the docs repo. It should be fine then. I am closing this issue (you're a great issue solver, @emdupre ).

I wonder why it takes so long to start binder, then.

**Comment by kchawla-pi** [comment]
Binder takes a while to setup the first few times, from what was mentioned
in their documentation. Once the server caches it for the user, it start
faster.
