### ISSUE TITLE
Confusion regarding FutureWarning: comparison to `None`

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2339]
While I was considering removing this warning
```py
nilearn/image/image.py:230: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
```
Generated by the last line in this section:
```py
    elif fwhm is not None:
        fwhm = np.asarray(fwhm)
        fwhm = np.where(fwhm == None, 0.0, fwhm)  # noqa: E711
```
It seems to me this code already relies on element-wise comparison of the array.
I find this a little confusing. Should I replace `fwhm == None` with `fwhm is None` or not?

**Comment by jeromedockes** [comment]
You are right, it seems to be doing element-wise comparison already.
Building an array containing None is not great, and even after
removing None the dtype of fwhm will be "object"
it is a bit weird that the function accepts None in fwhm when it is a
sequence.
anyway, I would replace these two lines with something like

  fwhm = np.asarray([0. if elem is None else elem for elem in fwhm])

**Comment by kchawla-pi** [comment]
I am not even sure what the line 
```py
fwhm = np.where(fwhm == None, 0.0, fwhm)
``` 
is necessary for. I saw warnings during tests (dunno if it's from this function or not) that if `fwhm` is set to `0.0` it is automatically set to `None`. What is this line doing? Why?

Your suggestion is better than the existing code but even then, this does not make sense to me.

**Comment by jeromedockes** [comment]
> is necessary for. I saw warnings during tests (dunno if it's from this function or not) that if `fwhm` is set to `0.0` it is automatically set to `None`. What is this line doing? Why?

smoothing with a bandwidth of 0 is like not smoothing

**Comment by kchawla-pi** [comment]
Yeah but in like 210 in the same file (same function), if fwhm == 0, it is set to None, so this section will not be executed if so.

**Comment by jeromedockes** [comment]
> Yeah but in line 210 in the same file (same function), if fwhm == 0, it is set to None, so this section will not be executed if so.

line 210 handles the case where fwhm is a single float (not a sequence)
equal to 0.0 :

    if isinstance(fwhm, (int, float)) and (fwhm == 0.0):

in this case it gets replaced by None and nothing (except possibly a
copy) is done to the array

later on the comparison

        fwhm = np.where(fwhm == None, 0.0, fwhm)  # noqa: E711

is for the case where fwhm is a sequence of 3 elements, some of which
may be None. These get converted to 0 just to treat all uniformly during
the conversion from fwhm to sigma (Full Width at Half Maximum to
standard deviation of the Gaussian kernel). 
then dimensions for which sigma is 0 do not get smoothed:

            if s > 0.0:
                ndimage.gaussian_filter1d(arr, s, output=arr, axis=n)

on a side note, these comparisons to 0 may fail because of
floating-point errors, and should be replaced with comparisons to a
small positive number such as np.finfo(np.float32).eps, eg fwhm > 1e-6,
s > 1e-6 rather than fwhm == 0., s > 0.

**Comment by kchawla-pi** [comment]
Okay. The warning then seems to be linked to the Numpy version. Until we bump it up.

**Comment by jeromedockes** [comment]
I haven't looked into it but it seems you can remove it by getting rid
of == None?
avoiding arrays of dtype object containing None entries is good anyway

**Comment by kchawla-pi** [comment]
O right you gave the idea already, sorry brain fart
