### ISSUE TITLE
Improvement of the conectome plotting functions with some common use cases

### ISSUE THREAD

**Issue by kfinc** [nilearn/nilearn#2460]
We prepared a [jupyter notebook](https://github.com/kfinc/nilearn-connectome-plotting/blob/master/nilearn_plotting_use_cases.ipynb) where we present some issues with current connectome plotting functions. The goal of suggested fixes is to simplify connectome plotting functions and make them more accessible to the user. We also found some bugs.

Specifically:

`plot_connectome`:
1. The default behavior of `node_color='auto'` is misleading, since it creates arbitrary colors for different nodes suggesting some kind of network division, or other information that the user did not provide. Also, the default 'auto' option is not described in the documentation. The default option should create uniformly colored nodes (e.g. gray).
2. The behavior of `edge_threshold` argument passed as a string representation of percentile is slightly counterintuitive considering common practice to report threshold as a percentage of strongest edges, i.e. 5% threshold would retain 5% of strongest edges, not 95% strongest edges.
3. Parameter `alpha` seems to have no effect on the resulting plot.

`plot_connectome_strength`:
1. It has two different functionalities: calculating nodal strength and plotting network nodes on top of the brain schematics. User has no control over centrality measure used to color-code nodes – e.g. it is impossible to use another nodal measure or treat negative connections in another way. The function seems to be very specific and it is not easily adaptable for user needs. Since the same functionality can be easily achieved using plot_connectome function adding few extra lines of code `plot_connectome_strenght` smells like *feature creep*.
2. Function focuses on providing color representation of node strength but does not offer the user option to easily include colorbar or limits for colormap (similar function `plot_connectome` has arguments `colobar`, `edge_vmin`, and `edge_vmax`), which makes it impractical for scientific use.
3. The name of the function is misleading because connectome (network edges) is not plotted. More appropriate name would be `plot_node_strenght`.
4. node_size argument should also accept an array-like object of individual node size like plot_connectome function. Documentation, however, specified that only auto and scalar are possible argument values. The function currently doesn't raise `TypeError` when the array-like object is provided, instead, the first element of the array is used (it is a bug, see below).
5. It is not straightforward to control node transparency which may be desirable.

Our general suggestion is to remove the function `plot_connectome_strenght` and to add a simple example of how to achieve the same effect using `plot_connectome` instead.

The notebook linked above presents some common use-cases, bugs, and suggestions that can be a starting point to implement some fixes during Nilearn Sprint or later. Let us know what you think!

**Comment by bthirion** [comment]
RThx for the very detailed analysis ! Please find some reactions below:


>     1. The default behavior of `node_color='auto'` is misleading, since it creates arbitrary colors for different nodes suggesting some kind of network division, or other information that the user did not provide. Also, the default 'auto' option is not described in the documentation. The default option should create uniformly colored nodes (e.g. gray).

The problem with uniformly colored nodes is that they're harder to distinguish. But I understand the concern on creating false impression. An alternative would be to used "50 shades or grey" (if I may), which would not give the impression of crypto-networks yet keep them distinguishable.  Any better suggestion ?

**Comment by bthirion** [comment]
>     2\. The behavior of `edge_threshold` argument passed as a string representation of percentile is slightly counterintuitive considering common practice to report threshold as a percentage of strongest edges, i.e. 5% threshold would retain 5% of strongest edges, not 95% strongest edges.

It should just be checked that this is consistent with the API (several functions in nilearn). numpy.percentile(98) indeed selects the top 2%. Could it be better documented ?

**Comment by bthirion** [comment]
regarding `plot_connectome_strength`, I agree with your comments. We have 2 options:
Either remove it or rename it to `plot_node_strength`. The idea would be that it may be further developed. Also, I have the feeling that the two functions definitely do a different jobs (edge importance vs node importance), hence I'd rather keep this as another function.
So, I'm in favor of renaming (with due deprecation cycle).

**Comment by bthirion** [comment]
What do other people think ?

**Comment by jeromedockes** [comment]
>>     1. The default behavior of `node_color='auto'` is misleading, since it creates arbitrary colors for different nodes suggesting some kind of network division, or other information that the user did not provide. Also, the default 'auto' option is not described in the documentation. The default option should create uniformly colored nodes (e.g. gray).
>
> The problem with uniformly colored nodes is that they're harder to distinguish. But I understand the concern on creating false impression. An alternative would be to used "50 shades or grey" (if I may), which would not give the impression of crypto-networks yet keep them distinguishable.  Any better suggestion ?

or `node_color="random"` ?

**Comment by jeromedockes** [comment]
> It should just be checked that this is consistent with the API (several functions in nilearn). numpy.percentile(98) indeed selects the top 2%. Could it be better documented ?

Indeed I think what is "intuitive" will vary from one person to the next
so what is essential is to document it explicitely

**Comment by bthirion** [comment]
> or `node_color="random"` ?

Yes, sounds good.

**Comment by GaelVaroquaux** [comment]
Thanks for this analysis. A few thoughts:

`plot_connectome`:
1. `node_color="random"` seems a better name. We can in addition turn this functionality off by default, if people find that it conveys the wrong message.
2. I agree that I keep forgetting which way around is `edge_threshold` percentile. However, it is consistent with all the threshold percentiles that we have. In addition, it seems to me difficult to change it given how long this function has existed and how much it is used.
3. That alpha thing might be a bug. We should look at the underlying code.

`plot_connectome_strength`:
1. It could be feature creep indeed. The reason why I was personally excited to add it is because it's the only way that I've been able to get a somewhat useful visualization of connectomes with many nodes. So I thought that it was cool to help others do it. But maybe it was a bad call.
2. we should add the colobar, vmin, and vmax arguments.
3. I worry that with a name such as `plot_node_strength` it would be harder to find.
4. The handling of arrays in `node_size` is a bug, and we should fix it.
5. Your comments make me think that we should add a `plot_markers` to plot the nodes (and reference it in the see also section of `plot_connectome` and `plot_connectome_strength`). We already have view_marker https://nilearn.github.io/modules/generated/nilearn.plotting.view_markers.html and the add_marker method https://nilearn.github.io/auto_examples/03_connectivity/plot_seed_to_voxel_correlation.html#plotting-the-seed-to-voxel-correlation-map

I see many items above that can be tackled and that I believe are consensual. We should probably tackle them first, in separate PRs (maybe grouping them a bit, but not too much).

**Comment by kbonna** [comment]
Hello,

I like the @GaelVaroquaux idea of adding `plot_markers` function. I agree that `plot_connectome_strength` function is focused on node importance as opposed to `plot_connectome` focusing more on connections. I believe, however that `plot_connectome_strenght` is not flexible enough, since it is quite common to visualize other node importance measures like betweenness centrality, local efficiency or clustering coefficient. As user, I'd be happy to have a function that allows me to pass node coordinates and arbitrary measure of node importance and produce a figure where nodes are color coded according to this measure. That function could replace `plot_connectom_strenght`, because providing node strenght (`np.sum(np.abs(adjacency_matrix, axis=0))`) would result the same output. 

Example function signature could look something like this:
```
def plot_markers(node_values, node_coords, node_size, 
                 node_cmap, node_vmin, node_vmax, 
                 output file, display_mode, figure, axes, title, colorbar):
    ...
```
Arguments:
- `node_values` would be array-like importance measure provided by the uses (e.g. node strength)
- `node_cmap`, `node_vmin`, `node_vmax` would control colormap and colormar limits used for `node_values` representation
- `colorbar=True` would show colorbar
- optionally this function could have `node_threshold` parameter (similar to `edge_threshold` parameter in `plot_connectome`) which would filter weakest nodes before drawing

I think that this sort of division of functions based on edge vs node importance would be very intuitive for the user, especially because they are quite similar in terms of argument naming and expected behavior. What do you think about this idea?

**Comment by bthirion** [comment]
Sounds good to me. Do you want to start a PR ?

**Comment by kbonna** [comment]
Sure. I can work on that, and submit PR when I finish the function.

We (me and @kfinc) can also work on other minor issues, i.e. `node_color='random'` and improving documentation for `edge_threshold` parameter and start separate PRs for those.

**Comment by bthirion** [comment]
Sure, this can go altogether in one PR.
