### ISSUE TITLE
Discussion: Should there be plotting in nilearn.reporting?

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2488]
There are a lot of plotting functions in nilearn.reporting. I do not really comprehend the logic that drove the choice of putting a function in plotting vs reporting. The whole content of the _plot_matrices file feels like I would expect it to be in plotting, as there is plotting.plot_matrix there.

I would expect to draw the line in the following way:
* Anything that simply does matplotlib plot should be in plotting
* Anything that outputs HTML reports should go in nilearn.reporting

**Comment by bthirion** [comment]
I had the impression that plotting functions were implicitly about image plotting, i.e. 2D/3D rendering of images. To me, design matrix or contrast matrix plotting are  different things. Note that they correspond more to model introspection, which makes it logical to have them in `reporting` module.
Now, there is the case of carpet plots: this is data not model, but on the other hand this is signals not images. I'm fine with having it in `plotting` module.

**Comment by GaelVaroquaux** [comment]
> I had the impression that plotting functions were implicitly about image plotting, i.e. 2D/3D rendering of images.

Nothing in the name says it (neither for "plotting", nor for
"reporting"). I think that it will be difficult for users to know where
to draw the line.

> To me, design matrix or contrast matrix plotting are different things.
> Note that they correspond more to model introspection, which makes it
> logical to have them in reporting module.

But where should plot_matrix lie, with this logic?

> Now, there is the case of carpet plots: this is data not model, but on
> the other hand this is signals not images. I'm fine with having it in
> plotting module.

But as you see, we are struggling to draw the line for many functions. As
a consequence, users will struggle too.

**Comment by bthirion** [comment]
Well, there is no solution that makes the separation for the users, as some plotting functions will be used mostly or uniquely in the reporting.
But, if people feel the distinction between 'mpl output' (plotting) vs 'html output' (reporting) is clear enough, that's good with me. Do other people have an opinion ?

**Comment by jeromedockes** [comment]
I don't think the distinction html vs matplotlib works very well because for
example the plotly and brainsprite plots are almost interchangeable whith
matplotlib ones, and probably belong in `plotting`, but produce html pages.

I think part of the confusion comes from the fact that we merged the nistats and
nilearn reporting packages, which do quite different things. In nilearn, the
reporting only contains utilities to manipulate html templates, and plotting and
other modules import `reporting`. in nistats, the reporting module does actual
computations and creates plots, and needs to import plotting.
therefore `reporting` does not naturally sit at the same place in the import
hierarchy with these two designs and mixing them is a bit tricky.

a bit more discussion on this topic happened in this pr:

  https://github.com/nilearn/nilearn/pull/2304#issuecomment-584202136
  https://github.com/nilearn/nilearn/pull/2304#issuecomment-584217174

To stick with nilearn's definition of reporting, to avoid the confusion
described in this issue and messy circular imports, I think that as
@GaelVaroquaux suggests much of the work done by nistats reporting should go
into plotting or the modules containing the reported objects (ie first level
model and second level model modules).

Finally, I think that the `ReporterMixin` should be removed and its
functionality placed into functions. Multiple inheritance is an unnecessary
complication here and forces importing `reporting` at the module level rather
than hidden inside reporting functions. We probably want to avoid that,
especially as long as a lot of computation and plotting survives in the
`reporting` package.

**Comment by bthirion** [comment]
Thx for the clarification.
I understand better and agree with your refactoring proposition (hence Gael's one). Note however that this represents a bit of work.
It should probably be addressed before the release. Anybody volunteers to address it ?

**Comment by emdupre** [comment]
One more clarification here -- we also discussed renaming one of the reporting functions in #2466. In looking through the codebase now I'm realizing I missed that Nistats had largely adopted the prefix 'make' for all of their reporting funtionality, whereas Nilearn reporting was establishing its own naming convention.

When we're doing the refactoring, I imagine we should also standardize these names. So, a follow-up question: should we delineate HTML vs matplotlib in the function name itself, in addition to the module it belongs to ?

**Comment by jeromedockes** [comment]
> When we're doing the refactoring, I imagine we should also standardize these names. So, a follow-up question: should we delineate HTML vs matplotlib in the function name itself, in addition to the module it belongs to ?

HTML vs matplotlib should be indicated in the function name for plotting
functions, ie the view_* vs plot_* functions

for reports, as this is completely different thing, I'm not sure what
distinction needs to be made? all reports are HTML pages, and none of
them are called plot_something (which wouldn't make sense)

BTW, in the reporting package, I only see two "make" public functions:
make_glm_report, and make_stat_maps (which should probably be private
anyway and is not imported in __init__.py). And if we want it to mimick
the NiftiMasker reports, make_glm_report will probably become a method
of the first and second level models.
Then there are make_first_level_design_matrix and
make_second_level_design_matrix in nilearn.stats

**Comment by emdupre** [comment]
> HTML vs matplotlib should be indicated in the function name for plotting
functions, ie the view_* vs plot_* functions

Sorry, yes, this was the connection I was hoping for (and likely missed that it was already made). My next question was if it should make sense to have reporting as `view_report` or `view_glm_report` rather than  `make` _or_ `generate` since the resulting objects behave like those generated with `view_` (e.g., the `open_in_browser` method).

**Comment by GaelVaroquaux** [comment]
> make_glm_report will probably become a method of the first and second level models.

Yes, I would favor this. With the same name. And push to have this be a
consistent thing across nilearn.

**Comment by jeromedockes** [comment]
> Sorry, yes, this was the connection I was hoping for (and likely missed that it was already made). My next question was if it should make sense to have reporting as `view_report` or `view_glm_report` rather than  `make` _or_ `generate` since the resulting objects behave like those generated with `view_` (e.g., the `open_in_browser` method). 

so for example: `masker.view_report()`? that makes sense. on the other
hand the plotting ones are really just showing an image that already
exists, while the reporting functions do create the report. I think both
work, no strong opinion on this.

**Comment by bthirion** [comment]
Indeed report generation can represent a substantial amount of computation (unlike view_* functions).

**Comment by thomasbazeille** [comment]
We didn't close this discussion with concrete steps to take, if we want to enhance consistency before the release would be a great time.

**Comment by thomasbazeille** [comment]
@GaelVaroquaux @bthirion @jeromedockes @emdupre we need to define concrete actions to take on this if we want to change modules organization of newly merged functions before the release (as long we can do so without deprecation cycle)

Otherwise if we don't find better compromise we can just agree the current organization is ok for now.

**Comment by jeromedockes** [comment]
Thanks a lot for the reminder @thomasbazeille. I think we had agreed on what to
do, but just didn't do it:

https://github.com/nilearn/nilearn/issues/2488#issuecomment-633538245
https://github.com/nilearn/nilearn/issues/2488#issuecomment-633628890

to summarize:

- the plotting functions that are in `reporting` at the moment that users might
  use directly go into `plotting`
- generation of nistats models' reports go into methods of these objects, with
  hidden imports of `plotting` and `reporting` where necessary
- not sure what we decided re. : renaming `make_report -> view_report`
- this refactoring should happen before the release

I can try to do it today.

**Comment by jeromedockes** [comment]
> I can try to do it today.

unless you or someone else has time to do it!

**Comment by jeromedockes** [comment]
Sorry to start again with this, but I started looking at what would need to be
done to move the glm reporting logic inside the glm package and it seems very
impractical. There are *many* helper functions, spread over several modules,
most of which use matplotlib or nilearn plotting functions.

Having `nilearn.plotting` and `matplotlib` hidden imports in all of these functions seems
weird and IMHO indicates this may not be the way to go.

what I would suggest is:

- keep the reporting logic in the `reporting` package
- move plotting functions such as `plot_design_matrix` that could be used
  directly by users to the `plotting` package and make them public, keep the
  helper plotting functions that only make sense to the glm reporter -- such as
  `_dmtx_to_svg_url` -- private and in `reporting`.
- hide the `reporting` import in `nifti_masker.py` inside a function -- avoid
  having to hide `input_data` imports as
  [here](https://github.com/nilearn/nilearn/blob/e26312be96fe5c0211da28889ddd3ab1bd0ddc49/nilearn/glm/thresholding.py#L140)
  and in some other places -- importing `input_data`, which is a core module,
  should never be an issue.
- move `HTMLDocument` back to `plotting` -- as it is used in plotting functions,
  and `reporting` needs to import `plotting` -- to avoid circular imports or
  workarounds -- such as
  [this](https://github.com/nilearn/nilearn/blob/e26312be96fe5c0211da28889ddd3ab1bd0ddc49/nilearn/reporting/__init__.py#L12)
- thus the reporting package is a client of both `plotting` and the core packages
  such as `glm`
- if we want to present report generation as methods of the reported objects,
  add the `generate_report` method to the GLM models, and have a hidden import
  of `reporting` and call to `make_glm_report` inside these methods

If we agree on this I can open a PR today; if we really want all of an object's
reporting logic implemented inside that object's methods I won't argue against
it but I will leave it to somebody else :)

**Comment by GaelVaroquaux** [comment]
Jerome, I find that all your suggestions are great and a good plan.

What do others think?

**Comment by jeromedockes** [comment]
pinging @emdupre and @kchawla-pi who wrote the reporting modules

**Comment by emdupre** [comment]
No strong opinions from me, that all sounds reasonable :+1: Thank you, @jeromedockes  !

**Comment by bthirion** [comment]
I think I agree with you: this is a minimum energy move toward more coherence.

I think it is OK to make report generation a method of GLM objects only in a later release, since this is not going to break the API.

**Comment by bthirion** [comment]
Thx for taking care of this :-)

**Comment by kchawla-pi** [comment]
Jerome's proposal here https://github.com/nilearn/nilearn/issues/2488#issuecomment-702078496 sounds the best to me as well.
