### ISSUE TITLE
[request feature] suggesting features for animal imaging data

### ISSUE THREAD

**Issue by dvm-shlee** [nilearn/nilearn#2493]
Hi Nilearn team,

I’m a preclinical fMRI researcher and want to conduct the Nilearn for my data analysis as well as visualization. One major concern is most of the visualization features are too optimized for human research in terms of generating the publishable level of figures while it also provides some flexibility to plot animal data.

So hope to suggest the following features as API to develop some animal-research-friendly features. This has been posted originally at Neurostars (https://neurostars.org/t/request-feature-suggesting-features-for-animal-imaging-data/6959?u=dvm-shlee) but copying here since this seems the better place.

Low-level API guide or instruction to tweak glassy template: Since I’m an animal-oriented researcher, I’m focussing a few species that others not formally do. The code seems only allowed MNI space, and there is no option currently to add additional space for this (hard codded to use only ‘brain_schematics_XX.json’ in ‘glass_brain_files’). So I’m suggesting to tweak the original code as below.
“glass_brain.py”

line 87, add
def _get_json_and_transform(direction, dirname = None):

line 104-105, add
____if dirname is None:
____[indent] dirname = os.path.dirname(os.path.abspath(__file__))
____[indent] dirname = os.path.join(dirname, ‘glass_brain_files’)

line 167, insert
________if ‘dirname’ in kwargs.keys():
____________dirname = kwargs[‘dirname’]
____________del kwargs[‘dirname’]
________else:
____________dirname = None

line 175, add
____json_filename, transform = _get_json_and_transform(direction, dirname)

The next feature will be decimal position annotation for the smaller brain., Below is my suggestion on updating a code.
“display.py”

line 260, add
____def draw_position(self, size, bg_color, decimal=False, **kwargs):
________if decimal:
____________text = ‘%s=%.{}f’.format(decimal)
________else:
____________text = '%s=%i’
line 262, modify ‘%s=%i’ to text as below
________ax.text(0, 0, text % (self.direction, self.coord),

line 1001, insert
________# use decimal for annotate position
________if ‘decimal’ in kwargs.keys():
____________decimal = kwargs[‘decimal’]
____________del kwargs[‘decimal’]
________else:
____________decimal = False

line 1011, add
________________display_axis.draw_position(size=size, bg_color=bg_color, decimal=decimal, **kwargs)

“img_plotting.py”

line 135, add
____if ‘decimal’ in kwargs.keys():
________decimal = kwargs[‘decimal’]
________del kwargs[‘decimal’]
____else:
________decimal = False

line 194, add
________display.annotate(decimal=decimal)

After adding the above code, with passing ‘decimal=2’ on any plotting method, the image will be as below.

![decimal](https://user-images.githubusercontent.com/7221078/82829358-16e07500-9e81-11ea-9b1b-bb1127695d42.png)

I haven’t tested the glass_brain, though, so I need the additional test to validate it. But I hope these features could be accepted into the Nilearn for animal researchers, and if this looks acceptable, I will generate a pull request according to your development guideline.

Thanks!

**Comment by bthirion** [comment]
Dear @dvm-shlee 
Thank you for your suggestion. 
My feeling however is that mouse imaging is beyond the scope of Nilearn. Maintaining the library for human images is already a hard task, hence we don't have the strength to support animal data.
The best that I can propose is to write a small module that would depend on Nilearn to perform the visualization task you need, while using Nilearn where you can.
I think that @TheChymera has already worked that way.
Best,

**Comment by jeromedockes** [comment]
the decimal in annotations is the same issue as #2042 . I guess the discussion there seems to suggest a PR would be welcome. the discussion also contains a way to achieve that in matplotlib, ie without changing nilearn code.

**Comment by jeromedockes** [comment]
> hence we don't have the strength to support animal data

I agree. to keep in line with @emdupre 's great talk at the nilearn dev days, maybe this should be made explicit somewhere?

**Comment by bthirion** [comment]
Yes, for the decimal thing I agree. What I meant is that we will keep human brain templates.

**Comment by dvm-shlee** [comment]
Thank you all for your comments on my request. for glassy brain, then I would make separate module as an addon to utilize tha nilearn. regarding the decimal, It looks like the discussion was made about an year, does any PR made for this request? If not, is it ok to generate PR for the decimal I'm as above code?

Thank you!

**Comment by jeromedockes** [comment]
> Thank you all for your comments on my request. for glassy brain, then I would make separate module as an addon to utilize tha nilearn. regarding the decimal, It looks like the discussion was made about an year, does any PR made for this request? If not, is it ok to generate PR for the decimal I'm as above code?

No PR was opened at the time, no. If you open one now, that would be
great, thank you. The approach you outline seems sound; it will be
easier to work out details once the PR is open.

Regarding the animal glass brains, as @bthirion and you say it is best
to implement that in a separate package.

**Comment by TheChymera** [comment]
@dvm-shlee as pointed out by others, nilearn clearly lacks the manpower to maintain out-of-the-box usability for animal data atm. Luckily the current code is fairly easy to build upon, which a number of people including myself have already done, and you are welcome to use and open issues on: https://github.com/IBT-FMI/SAMRI

To address your specific questions:

1. **Mouse coordinate space:** we have generated an RAS-oriented atlas with the origin at bregma (this is pretty cool because it allows you to do imaging, analysis and perform operations in the same coordinate space). We actually have that under review, and you can see the atlas here ( https://www.biorxiv.org/content/10.1101/619650v2.full ), download it [here](http://chymera.eu/distfiles/mouse-brain-atlases-0.5.3.tar.xz), and see how it was generated [here](https://github.com/IBT-FMI/mouse-brain-atlases_generator).

2. **Mouse glass brain:** I have tried to sell that to the nilearn team [a while ago](https://github.com/nilearn/nilearn/issues/797), but have since given up. What we now use is a blender-based automatic rendering of the surface and statistic map mesh (figure 3a, here: https://www.biorxiv.org/content/10.1101/2020.04.03.023648v1.full ). This is very easy for you to use API-wise, since it just extends the orthoplanar plotting function. That figure, once you install SAMRI, can be generated with [a single function call](https://bitbucket.org/TheChymera/opfvta/src/d2e03923be8aa6218c060ca7336b53b01ba166ed/scripts/map_block_filtered_controlled.py#lines-6). I have mainly given up on creating a glass brain, since we have 3D plotting working so nicely and reliably, but if you really really want to, we could do that based on SVG files like the ones seen in [figure 1](https://www.biorxiv.org/content/10.1101/2020.04.03.023648v1.full), which I am happy to share with you.

3. **Decimal-level coordinates:** we've got that implemented in a slice-wise plotting function (example in [figure 4c](https://www.biorxiv.org/content/10.1101/2020.04.03.023648v1.full), API call [here](https://bitbucket.org/TheChymera/opfvta/src/d2e03923be8aa6218c060ca7336b53b01ba166ed/scripts/features_filtered_coronal.py#lines-15)). We haven't implemented coordinates for orthoplanar slicing, but if you would wish to submit a PR of what you have proposed here on SAMRI, I'd definitely be interested.

**Comment by dvm-shlee** [comment]
@TheChymera Thank you for sharing great work and introducing your project. Looks you made amazing works for the animal imaging! Realizing there are also some similar works our group has done for fMRI in rats.  Regarding the glassy brain, I will check your SAMRI project and also check if there is anything I can contribute.

@jeromedockes @bthirion Thank you for discussion and provide information regarding this request, I just generated PR for positional annotation, and revert the changes I made on glassy brain module.

**Comment by TheChymera** [comment]
@dvm-shlee glad you like it. If you want I'd be happy to try to merge our work, in order for things to survive and grow it's important to reach a critical mass of contributors. This no longer has anything to do with the nilearn issue tracker, though, so I think it's best we move to the SAMRI issue tracker for specific issues (e.g. glass brain), or you can write to me directly for more general questions regarding small animal MRI collaboration. That's “horea” at the domain name mit.edu.
