### ISSUE TITLE
fetch_abide_pcp returns 403 error

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2502]
A user reported that the `fetch_abide_pcp` function is currently returning a 403 error and has been since at least yesterday. Code to reproduce:

```python
from nilearn import datasets
datasets.fetch_abide_pcp()
```

Checking the dataset URL (https://s3.amazonaws.com/fcp-indi/data/Projects/ABIDE_Initiative) in-browser confirms the problem is server side. Do we have a good contact point for this data set ? I'm happy to reach out to CMI, but I'm not sure if there's another, better contact.

EDIT: I've contacted them and will report back.

**Comment by bthirion** [comment]
No better suggestion than contacting CMI. Thx !

**Comment by mwshinn** [comment]
I'm having the same problem.  If you don't hear back, the PCP has an ABIDE repo with an issue tracker we could try as well, though it doesn't seem to be very active: https://github.com/preprocessed-connectomes-project/abide/issues  I tried the official script in their repo as well which gives the same error as nilearn, confirming the sever-side issue isn't due to them changing the official url.

**Comment by besteaydemir** [comment]
Hey, thanks for contacting them. The problem seems to have resolved for me, I am able to download and use the data. I hope it is available for everyone. Thanks again!

**Comment by emdupre** [comment]
I didn't hear back from them, but I can confirm the problem is resolved on my side as well so I'll close this. Thanks everyone !
