### ISSUE TITLE
plot_prob_atlas error: No contour levels were found within the data range

### ISSUE THREAD

**Issue by vnckppl** [nilearn/nilearn#2513]
**Problem**
plot_prob_atlas is not plotting atlas outlines

**Approach**
I have several 4D image files each containing 28 binary masks. I want to plot the outlines of the 28 ROIs per file. I used:
```
binmask = nb.load('/path/to/4D_binary_mask.nii.gz')
display = plotting.plot_prob_atlas(binmask)
```

For most but not all files, this results in several errors, all in the form of:
> /Users/vincent/Data/tmp/env/lib/python3.8/site-packages/nilearn/plotting/displays.py:97: UserWarning: No contour levels were found within the data range.
>   im = getattr(ax, type)(data_2d.copy()

I checked and made sure that none of the 3D volumes within the 4D volume are empty. All 4D files are created by the same pipeline and I can't detect differences between these files other than differences in the location of the ROIs within these 4D files. 

I am using the following software:
Python 3.8
Nilearn 0.6.2

**Comment by emdupre** [comment]
Hi ! This is a question that would be better suited to [NeuroStars](https://neurostars.org), as it's about the usage of the software rather than an issue in the software itself.

The problem here is likely that you're using `plotting.plot_prob_atlas`, which expects a probabilistic atlas rather than a binary mask. You likely want something more like `add_contours`. You can see [an example here](https://nilearn.github.io/auto_examples/01_plotting/plot_haxby_masks.html#sphx-glr-auto-examples-01-plotting-plot-haxby-masks-py).

I'll close the discussion here but would be happy to continue it on NeuroStars ! Just use the `nilearn` tag. Thanks !

**Comment by vnckppl** [comment]
Hi Elizabeth, Thank you for your reply. I agree that there are better ways of plotting the data, but the tool does not seem to be the culprit here. In fact, I experience the exact same problems with `add_contours`. I'll refer to my follow-up question here, just in case someone else may land here who experiences the same issue: https://github.com/nilearn/nilearn/issues/2537
