### ISSUE TITLE
the readme file of destrieux2009 atlas is wrong

### ISSUE THREAD

**Issue by YipengUva** [nilearn/nilearn#2516]
I used "nilearn.datasets.fetch_atlas_destrieux_2009()" to download the destrieux_2009 atlas. The mni152 atlas and its label information are very useful for my research. 

However, the readme file is wrong. Therefore, I am not sure if I should trust the downloaded atlas or not. It is great if the correct version readme file can be provided.

Regards, Yipeng

**Comment by bthirion** [comment]
Thanks for reporting.
Would you be able to fix this ?

**Comment by YipengUva** [comment]
Thanks very much for your reply, bthirion. I hope I have the ability to fix it. However, I am a statistician, and just begin to work in the neuroimaging area. Sorry about it.

**Comment by emdupre** [comment]
Thanks for reporting, @YipengUva ! Could you clarify what is wrong with the file ? And could you confirm that you mean [this description](https://github.com/nilearn/nilearn/blob/master/nilearn/datasets/description/destrieux_surface.rst) ?

**Comment by YipengUva** [comment]
Yes. The downloaded destrieux_2009 fold contains the following files, destrieux2009_rois.nii.gz, destrieux2009_rois_labels.csv, destrieux2009_rois_labels_lateralized.csv, destrieux2009_rois_lateralized.nii.gz and a readme file. The description in the readme file is wrong. I have no way to reproduce it.

The readme file contains:

Background
==========
The 'Destrieux' cortical atlas is based on a parcellation scheme
that first divided the cortex into gyral and sulcal regions,
the limit between both being given by the curvature value of the surface.
A gyrus only includes the cortex visible on the pial view,
the hidden cortex (banks of sulci) are marked sulcus.
The result is a complete labeling of cortical sulci and gyri.

Files in Folder (Excluding README)
==================================
1) rh_destrieux2009_rois.nii.gz
2) lh_destrieux2009_rois.nii.gz
3) destrieux2009_rois_labels.csv

Descriptions of files
=====================
1) rh_destrieux2009_rois.nii.gz is a right hemisphere volume consisting
of 76 rois projected into a 2mm isotropic MNI152 space.
The volume is obtained from FreeSurfer's fsaverage template, by transforming
the annotation to a volume with mri_label2vol command as follows :
mri_label2vol --subject fsaverage --hemi rh --annot rh.aparc.a2009s.annot
--reg reg.2mm.dat --temp brain.mgz --fillthresh 0. --proj frac 0 1.5 .1
--o rh_destrieux2009_rois.nii.gz

2) lh_destrieux2009_rois.nii.gz is the left hemisphere counterpart volume.

3) destrieux2009_rois_labels.csv is the file that contains the rois labels.

References
==========
Fischl, Bruce, et al. "Automatically parcellating the human cerebral cortex."
Cerebral cortex 14.1 (2004): 11-22.

Destrieux, C., et al. "A sulcal depth-based anatomical parcellation
of the cerebral cortex." NeuroImage 47 (2009): S151.

**Comment by emdupre** [comment]
Thanks for confirming, @YipengUva. You can see the [function definition here](https://github.com/nilearn/nilearn/blob/cc0f43ce329bda5af2eb4cb01b7207ed4ef24b9c/nilearn/datasets/atlas.py#L93-L148).

It seems that we could either update the RST file on the NITRIC archive, or change how the description is generated. I'm leaning towards the second route, as I'm unsure who originally uploaded that archive or how we can get access to modify it.

**Comment by YipengUva** [comment]
Thanks for your reply, emdupre. My concern is that how the atlas is generated from the original

**Comment by emdupre** [comment]
@jeromedockes do you have access to the NITRIC archives for Nilearn ? In particular, this one: https://www.nitrc.org/frs/download.php/7739/

It seems the included README is out-of-date with the rest of the archive.

**Comment by jeromedockes** [comment]
> @jeromedockes do you have access to the NITRIC archives for Nilearn ? In particular, this one: https://www.nitrc.org/frs/download.php/7739/

Sorry, I don't (fsaverage surfaces are in a separate collection).

**Comment by bthirion** [comment]
I think I can do it.
If somebody has the right Readme, I'm happy to take it, otherwise i'll figure it by myself.

**Comment by emdupre** [comment]
Thanks, @bthirion ! I think it would need to read something like the following :point_down: 

<details>

Background
----------------

The 'Destrieux' cortical atlas is based on a parcellation scheme
that first divided the cortex into gyral and sulcal regions,
the limit between both being given by the curvature value of the surface.
A gyrus only includes the cortex visible on the pial view,
the hidden cortex (banks of sulci) are marked sulcus.
The result is a complete labeling of cortical sulci and gyri.

Files in Folder (Excluding README)
------------------------------------------------

1. destrieux2009_rois.nii.gz
2. destrieux2009_rois_labels.csv

Optionally, if the lateralized argument is set to True, the archive will also contain:

3. destrieux2009_rois_lateralized.nii.gz
4. destrieux2009_rois_labels_lateralized.csv

Descriptions of files

1. destrieux2009_rois.nii.gz is a volume consisting
    of 75 rois projected into a 2mm isotropic MNI152 space.
2. destrieux2009_rois_labels.csv is the file that contains the ROI labels.
3. destrieux2009_rois_lateralized is a volume consisting of 150 rois,
    75 for each hemisphere, projected into a 2mm isotropic MNI152 space.
4.  destrieux2009_rois_labels_lateralized is a file that contains the ROI
     labels for the lateralized volume.

References
---------------

Fischl, Bruce, et al. "Automatically parcellating the human cerebral cortex."
Cerebral cortex 14.1 (2004): 11-22.

Destrieux, C., et al. "A sulcal depth-based anatomical parcellation
of the cerebral cortex." NeuroImage 47 (2009): S151.

</details>

Of note, I've removed the provided command used to generate the `rh` file, since I'm not sure if the current file was generated from right and left separately and combined, or through another fashion. I also modified the number of ROIs from 76 to 75, since the `0` label indexes the background (which I wouldn't consider to be a unique ROI).
