### ISSUE TITLE
On the possibility of a `dev` branch?

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#2524]
Dear devs and collaborators,

I was wondering whether the nilearn project has ever considered having a dev branch where PRs would be merged more quickly for testing.
I think that'd be useful for users who would like to have features awaiting release (like nilearn.glm, and some of the new plotting and surface functionality), or for users who would like to help the project by giving feedback on alpha code before it is released.

I see a dev branch advantageous in that it lowers the barrier for contribution, allows testing new features, and helps defining APIs before they are released. It also may help to reduce issues with PRs that stall and lead to git history chaos.

On the flipside, a dev branch may increase the burden on main devs, as contributors may not be willing to go the extra mile in adding proper docs and tests. Perhaps contributions to dev would only be acceptable if they contain tests and at least mock examples?

Otherwise, what is the recommended way of testing beta features?

**Comment by bthirion** [comment]
But the master branch is actually the dev branch ?

I think that the point you're discussing is rather that the release rhythm is too slow. There is a reason for that: the new release will contain Nistats merge, which is still requiring some important work to ensure that the API is solid. 

Sorry if I misunderstood.

(and of course I'm petrified by anything that will "increase the burden on main devs"  ;-)  but note that we're never going to consider features that come without tests, docs etc.)

**Comment by GaelVaroquaux** [comment]
The idea of prototyping is a very good one, and it is true that solid
prototypes help integrating code. However, it is better that these
prototypes live outside the codebase rather than in a branch. Indeed, the
branch is difficult to retrieve for users, and requires maintenance
effort to keep up to date.

The bigger the branch grows, the harder it is to merge stuff in it, and
to transfer stuff to master.

Prototyping has always been a challenge in projects. Projects have had
sandboxes, for instances. These tends to accumulate cruft and die.

I don't know well how to answer this need, sorry.

**Comment by dangom** [comment]
Closing. See #2531
