### ISSUE TITLE
nistats: adding two_sided flag to get_clusters_table would result in more consistent API?

### ISSUE THREAD

**Issue by kbonna** [nilearn/nilearn#2547]
Hello,

I've been recently using nistats to report results from fMRI data analysis. I wanted to perform two-sided test for my 2nd level spm, since I was interested in both increased and decreased brain responses. `map_threshold` function provide flag `two_sided` which nicely adjust significance level preserving clusters with both positive and negative test statistic values. 

Next I wanted to use `get_clusters_table` function to pool information about peak coordinates. However, this function can only report peaks above `stat_threshold` (basically neglecting negative test stat values). I made a workaround to make it consistent with `map_threshold` – I multiplied my spm by (-1), reapplied `get_clusters_table` and then merged two tables together. 

Do you think that adding `two_sided` flag and its functionality to `get_clusters_table` is a good idea?

**Comment by bthirion** [comment]
Sorry for the late answer. Yes, I think that this is a good idea.
Do you want to take care of that ?

**Comment by tsalo** [comment]
Is it worth it to take a cue from AfNI and support one-sided, two-sided, _and_ bi-sided?

**Comment by bthirion** [comment]
Sorry, can you explain the diff btw two-sided and bi-sided ?  Thx

**Comment by tsalo** [comment]
Two-sided clustering combines positive and negative values as single clusters, while bi-sided clusters positive and negative values separately. To be honest, I've never understood the purpose of two-sided clustering as they define it, but I imagine there's a use for it since it's been supported in AfNI for so long (e.g., in [`3dClusterize`](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dClusterize.html)).

It's not something I know a lot about, but it would impact this case in that it would require a parameter that accepts a string (e.g., `sided='one'`) instead of a bool (e.g., `two_sided=False`), so I thought I'd bring it up.

**Comment by bthirion** [comment]
Well, I'm not interested in having a method for which we don't have a use case... from what I understand what Afni calls `two-sided` is not a sensible approach... the problem is that `two-sided` is used in other packages for what Afni calls `bi-sided`.
So, I'd rather not implement this feature and keep the argument as-is.
Do you have strong feelings about that ?

**Comment by tsalo** [comment]
That sounds good to me. I just thought I'd bring it up in case it was worth the extra effort.

**Comment by alexenge** [comment]
Is there any news on making `two-sided` an option for `get_clusters_table`? I feel like this would be a very useful enhancement (but unfortunately I don't think my Python skills suffice to contribute – not yet, at least).

**Comment by tsalo** [comment]
Took a quick crack at it. Just opened #2719.

**Comment by alexenge** [comment]
Please excuse the delayed reply – I've just tested this with a *z*-map containing both negative and positive clusters and the function is displaying all of them as expected. Thanks a lot!
