### ISSUE TITLE
Add explanations for 1st and 2nd level for glm

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2599]
Add a few lines somewhere in the doc to explain what are `glm` `first` and `second levels` which might not be obvious for researchers from other fields. 
Note: We could also put a link to these explanations in the html reports.

**Comment by tpremrud** [comment]
@NicolasGensollen Thank you for opening the issue!
Are these (i.e., https://nilearn.github.io/dev/glm/first_level_model.html, https://nilearn.github.io/dev/glm/second_level_model.html) the documentation links to `first level` and `second level` GLMs, respectively?

It seems there are some information in those pages already. With that, is this issue still open as I would love to contribute!

Thank you!!!

**Comment by bthirion** [comment]
You're welcome ! Please review carefully the existing doc and identify missing stuff.

**Comment by Remi-Gau** [comment]
@tpremrud 

From @NicolasGensollen original message I am not sure exactly what information is actually missing.

I do find the summaries for those pages good enough. But then again I have been dealing fMRI GLMs for a while now, so I think I may not even realize what implicit information may be missing and that I am filling in. So please, have a look and don't hesitate to point out what is missing in your opinion.

Random thoughts...

Maybe the issue was referring to what the main classes for first and second level actually do ?

- https://nilearn.github.io/dev/modules/generated/nilearn.glm.first_level.FirstLevelModel.html
- https://nilearn.github.io/dev/modules/generated/nilearn.glm.second_level.SecondLevelModel.html

Or maybe we should "explain" things in terms of:
- "run level GLM"
- "subject level GLM"
- "group level GLM"
as different software may mean different things for First and Second level.
Also to align better with the Nodes of the [bids stats model formalization](https://bids-standard.github.io/stats-models/_autosummary/bsmschema.models.Node.html).

**Comment by tpremrud** [comment]
@Remi-Gau Thank you for pointing out that it seems complete already! I could definitely fill in the missing pieces in terms of implicit information, as I am not an expert in fMRI GLM.

With that, I think both random thoughts could be taken care of, but I am struggling to understand what you meant by 'what the main classes for first and second level actually do'. Is it expanding more on the class definition given as 'Implement the General Linear Model for single run [fMRI](https://nilearn.github.io/dev/glossary.html#term-fMRI) data.' for the first level? Or are you talking about expanding the function definition more, which might not be clear enough (e.g., fit method)?

For the second random thought, where do you think we should address that diversity in meanings? I think the GitHub pages would be a great place to update, but I'm not sure if I'm missing anything.

Thank you so much!
PS: This is my first time ever contributing to a GitHub repo issue, so I am excited to contribute but maybe a bit too nervous to see what is going on; hence, I appreciate any help! :)

**Comment by Remi-Gau** [comment]
> I am struggling to understand what you meant by 'what the main classes for first and second level actually do'. Is it expanding more on the class definition given as 'Implement the General Linear Model for single run [fMRI](https://nilearn.github.io/dev/glossary.html#term-fMRI) data.' for the first level? 

I was more thinking about this one


> For the second random thought, where do you think we should address that diversity in meanings? I think the GitHub pages would be a great place to update

Maybe adding some explanation in [this page of the doc](https://nilearn.github.io/dev/modules/glm.html)?

Corresponding to this file: https://github.com/nilearn/nilearn/blob/main/doc/modules/glm.rst

Or in [the "index" page of the GLM section of the user guide](https://nilearn.github.io/stable/glm/index.html)?

Corresponding to this file: https://github.com/nilearn/nilearn/blob/main/doc/glm/index.rst

> Thank you so much! PS: This is my first time ever contributing to a GitHub repo issue, so I am excited to contribute but maybe a bit too nervous to see what is going on; hence, I appreciate any help! :)

Woohoo!!! Exciting!!! Though thinking back on my first ever contribution, I can relate to the being nervous part.

If things are not clear: don't hesitate to ask.

Before you jump in, make sure you have look at the "how to contribute" section of the doc.

Especially this part: https://nilearn.github.io/stable/development.html#setting-up-your-environment

You could also come to the drop in hours if you need guidance on the content of your contributions or how to go about it.

https://github.com/nilearn/nilearn/issues/3211

**Comment by tpremrud** [comment]
After some guidance from @Remi-Gau, I have done a PR on comparing the meaning of different GLM (first, second, and third-level models) for FSL and SPM, with the possible extension of extending to comparing with those of AFNI.

Feedbacks are truly appreciated! :D
