### ISSUE TITLE
The reports for GLMs are not well visible in notebooks

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2602]
Running the following example in a notebook:
http://nilearn.github.io/auto_examples/02_decoding/plot_haxby_glm_decoding.html#generating-a-report

Give a report that is too wide for the container:
![image](https://user-images.githubusercontent.com/208217/98979735-ff26a700-251b-11eb-920b-b72184842921.png)

The HTML and the CSS need a bit of work. Some of it should be borrowed from the reporting generated for the NiftiMasker

**Comment by NicolasGensollen** [comment]
@GaelVaroquaux I had a look at this, and it seems like the report default dimensions are set to `width=1600` and `heigth=800`, but they are exposed to `make_glm_report`, such that you should be able to tune the report dimensions:
 
![glm_report_dims](https://user-images.githubusercontent.com/2639645/99541054-a25e3d00-29b0-11eb-94d2-191c66671647.png)

I'm not sure this answers your point or not, but I prefer to check before digging in the HTML/CSS of the report.

**Comment by GaelVaroquaux** [comment]
This is indeed better.

The core of my point is that the NiftiMasker report does it right by
default. I don't remember how it's done, and whether it's done via a
pre-specified width.

**Comment by NicolasGensollen** [comment]
@GaelVaroquaux after looking a little bit more into this, I think this is because the `glm` report is an instance of the `HTMLDocument` class, which wrapps the html code inside an `iframe` when calling `_repr_html`:

https://github.com/nilearn/nilearn/blob/82f4075d8a8ea9aec25e66bd87ebb79a6be6d32f/nilearn/plotting/html_document.py#L88-L94

On the other hand, the `NiftiMasker` generates an instance of `HTMLReport` which inherits from `HTMLDocument` but basically splits the body of the html code from the header, such that `_repr_html` simply returns the body without wrapping the html code inside an iframe:

https://github.com/nilearn/nilearn/blob/82f4075d8a8ea9aec25e66bd87ebb79a6be6d32f/nilearn/reporting/html_report.py#L177-L182

I'm still unsure whether I should try to make the `glm` model report an `HTMLReport`, or whether I should tweak the `HTMLDocument` class to store the body and header code seperately to mimic what `HTMLReport` does.

I believe the first option should be the most appropriate in order to have consistent reporting across nilearn although it certainly requires more work.

**Comment by GaelVaroquaux** [comment]
Good detective work! I think that you found the important point, indeed.

> I'm still unsure whether I should try to make the glm model report an HTMLReport, or whether I should tweak the HTMLDocument class to store the body and header code seperately to mimic what HTMLReport does.

> I believe the first option should be the most appropriate in order to have consistent reporting across nilearn although it certainly requires more work.

I agree. I think that in the long term, it will help having more uniform code.

**Comment by jeromedockes** [comment]
> I'm still unsure whether I should try to make the `glm` model report an `HTMLReport`, or whether I should tweak the `HTMLDocument` class to store the body and header code seperately to mimic what `HTMLReport` does.
>
> I believe the first option should be the most appropriate in order to have consistent reporting across nilearn although it certainly requires more work.
>

yes the first option. the reason `HTMLDocument` outputs an iframe is to
isolate it from the page it is embedded in (load javascript libraries
only once, easily have unique element ids etc.) -- HTMLDocument is used
for interactive javascript plots. AFAIK reports are pure html and css so
it is less of an issue for them which is why HTMLReport doesn't use an
iframe

**Comment by jeromedockes** [comment]
but of course if it is just a question of size the height and width of
the iframe are parameters in the document's __init__

**Comment by NicolasGensollen** [comment]
Fixed in #2613
