### ISSUE TITLE
math_img loses header information

### ISSUE THREAD

**Issue by robbwh** [nilearn/nilearn#2645]
In nilearn 0.7.0, using math_img to get the first 180 dynamics of an image. 

```
img = math_img("img[:,:,:,0:180]",img=img)
``` 
Then I save the image and look at the header with fslhd.

new header has pixdim4 as 1:

```
size of header	348
data_type	FLOAT64
dim0		4
dim1		144
dim2		144
dim3		41
dim4		180
dim5		1
dim6		1
dim7		1
vox_units	Unknown
time_units	Unknown
datatype	64
nbyper		8
bitpix		64
pixdim0		-1.000000
pixdim1		1.647059
pixdim2		1.647059
pixdim3		3.000000
pixdim4		1.000000
```

Original header here has pixdim4 as 2:

```
size of header	348
data_type	INT16
dim0		4
dim1		144
dim2		144
dim3		41
dim4		360
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		-1.000000
pixdim1		1.647059
pixdim2		1.647059
pixdim3		3.000000
pixdim4		2.000001
```

I'm using nibabel to do this now, but this might need fixing.

**Comment by bthirion** [comment]
Indeed, thx. Do you want to open a PR to address this ?

**Comment by tsalo** [comment]
What would be the expected behavior when two images with different header information are used? The easiest example I can come up with would be adding two 4D images with different TRs. Would we want to raise an exception in that case?

**Comment by bthirion** [comment]
I would expect the same behavior as if the affine or any other parameter was different.

**Comment by man-shu** [comment]
Looking at this, I could reproduce the issue in pure-python: 

```python
from nilearn import image
from nilearn import datasets
from pathlib import Path

# Get example data
haxby_data = datasets.fetch_haxby()
data_root = Path(datasets.get_data_dirs()[0])
haxby_data_dir = data_root / "haxby2001" / "subj2"

# Load functional data
img = image.load_img(haxby_data_dir / "bold.nii.gz")
# slice func image using math_img
sliced_img = image.math_img("img[..., 0:180]", img=img)

print(img.header["pixdim"])
# returns array([1.  , 3.5 , 3.75, 3.75, 2.5 , 0.  , 0.  , 0.  ], dtype=float32)

print(sliced_img.header["pixdim"])
# returns array([-1.  ,  3.5 ,  3.75,  3.75,  1.  ,  1.  ,  1.  ,  1.  ], dtype=float32)
```

I think the issue lies in [`nilearn.image.math_img`#L1071](https://github.com/nilearn/nilearn/blob/a950195e83d6f9af64fa3166369427b8a58d1066/nilearn/image/image.py#L1071) as the default for `copy_header` is `False` in `new_img_like`, and we could simply set it to `True`.

We would also need to check for another use case where one could do math_img over two images with the same affine but different TRs. As discussed above, we want to throw a similar error as when the affines are different.

However, when I wanted to test that I found that **the same issue exists with resampling functions as they don't copy the header and the TR is not carried over**. Could be a separate issue if doesn't already exist.
