### ISSUE TITLE
plotting.view_markers as an ipywidget

### ISSUE THREAD

**Issue by bendichter** [nilearn/nilearn#2646]
Hi, I really like `plotting.view_markers` and I'd like to use it in a larger ipywidgets project, [NWB Widgets](https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets). The problem is that I would need it as an `ipywidgets.Widget` so that it fits into the nested widget environment. I took a look at [a convo between your team and ipyvolume a few years back about transparency](https://github.com/maartenbreddels/ipyvolume/issues/56). It's good to see you were able to solve the transparency issue with Plotly. We have made Plotly figures into widgets and used them in this way, but it appears you are using the javascript API for plotly, not the Python API, so I'm not sure if it would be possible in this case. I'm curious why you aren't using the Python API. Was this developed before the triangular mesh functions were available?

Wrapping the output like `ipywidgets.HTML(view.html)` runs, but the brain doesn't render.

If I am not able to get the output of `plotting.view_markers` into an `ipywidgets.Widget`, I think I'm going to have to recreate major parts of it using the Plotly Python API so that I can get it into my framework. I'd really rather use nilearn, so it would be great if anyone has suggestions how to get this to fit.

**Comment by jeromedockes** [comment]
Hi, we used the javascript plotly API because (1) we did not want to add a dependency on Plotly and (2) we wanted the interactive plots to be static, standalone pages that can be saved and shared. However, we are now planning to add an optional dependency on Plotly (python library) and when it is installed also offer the figures created by the `view_*` functions as python plotly figures. the main motivation is that it would enable saving them as png , and I think it would also make it possible to turn them into ipywidgets. I'm not really sure when it will be added though -- if by any chance you would like to work on this enhancement let us know!

With the current version of nilearn I guess as you pointed out the easiest way would be to write the code to create the figure with the plotly python API. I think some parts of https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/html_connectome.py (eg from the `_get_connectome` function) can be copy-pasted to help prepare the inputs to the plotly python figure

**Comment by jeromedockes** [comment]
> Wrapping the output like ipywidgets.HTML(view.html) runs, but the brain doesn't render.

and have you tried `ipywidgets.HTML(view.get_iframe())` ?

**Comment by jeromedockes** [comment]
@bendichter  this seems to work for me:
```python
from nilearn import plotting
import ipywidgets
from IPython.display import display

coords = [[0, -52, 18], [-46, -68, 32]]

html = plotting.view_markers(coords)
widget = ipywidgets.HTML(html.get_iframe())

display(widget)
```

is this what you wanted?

**Comment by jeromedockes** [comment]
![Screenshot from 2021-01-07 14-50-27](https://user-images.githubusercontent.com/9196501/103938136-c5c37f80-50f7-11eb-87d0-6a3a9fe4c6d9.png)

**Comment by bendichter** [comment]
thanks!
