### ISSUE TITLE
compute_contrast in FLM fails when used on multiple runs with different shapes of design matrices 

### ISSUE THREAD

**Issue by hyruuk** [nilearn/nilearn#2687]
Context : 
I am trying to obtain activation maps for a contrast between two conditions. I have several runs that I want to input in a FLM. For each run, I have a confounds file generated by [fMRIPrep](https://fmriprep.org/en/stable/). These files include the cosines for drift compensation. Because the length of each run varies a little bit, the number of cosines generated in the confounds files varies too. I first load the confounds file with [load_confounds](https://pypi.org/project/load-confounds/), then I generate the design matrices with [make_first_level_design_matrix](https://nilearn.github.io/modules/generated/nilearn.glm.first_level.make_first_level_design_matrix.html), by passing the confounds in add_regs.

Problem : 
When I use runs with different number of cosines from the confounds files (so, design matrices of the different runs have a different number of columns) the call to compute_contrast fails. It does not fail when I use runs with identical number of cosines.
I've found a [similar problem](https://github.com/nilearn/nilearn/issues/2394) in the issues, but since in my case the two conditions of my contrast are present in all runs, I thought that it might be a related but different issue. 

Or maybe, as some responses to the other issue seemed to suggest, this is a feature and not a bug ? If that's the case, how should I approach this question instead ?

Thanks in advance for your help !

Nilearn version:
0.7.0

### Expected behavior
compute_contrast should (?) be able to handle a list of design matrices with varying number of columns.

### Actual behavior
When two design matrices with a different number of columns are passed to compute_contrast, the function fails and returns the following error : 

`
~/anaconda3/envs/hyruuk_shinobi_behav/lib/python3.8/site-packages/nilearn/glm/contrasts.py in compute_contrast(labels, regression_result, con_val, contrast_type)
     92         for label_ in regression_result:
     93             label_mask = labels == label_
---> 94             resl = regression_result[label_].Tcontrast(con_val)
     95             effect_[:, label_mask] = resl.effect.T
     96             var_[label_mask] = (resl.sd ** 2).T

~/anaconda3/envs/hyruuk_shinobi_behav/lib/python3.8/site-packages/nilearn/glm/model.py in Tcontrast(self, matrix, store, dispersion)
    198             raise ValueError("t contrasts should have only one row")
    199         if matrix.shape[1] != self.theta.shape[0]:
--> 200             raise ValueError("t contrasts should be length P=%d, "
    201                              "but this is length %d" % (self.theta.shape[0],
    202                                                         matrix.shape[1]))

ValueError: t contrasts should be length P=49, but this is length 47`

### Steps and code to reproduce bug

I joined an pdf file that shows my code and the outputs. First cell are imports. Second cell shows expected behavior, with two runs that share the same number of confounds. Third cell shows the bug, the code fails to generate the contrast because the two runs have different number of confounds (44 and 46). Fourth cell shows the same runs as in the second cell (the one that works), but I manually removed one of the cosines (to make sure that the number of columns of the design_matrix would differ), and that recreates the issue.

[bug_flm_confounds.pdf](https://github.com/nilearn/nilearn/files/5936005/bug_flm_confounds.pdf)

```python

```

**Comment by bpinsard** [comment]
I was able to reproduce the error on the same data. ;) 
With debugging, I was able to understand that calling `model.compute_contrasts(["contrast_str"]*n_runs)` would work but not `model.compute_contrasts("contrast_str")` due to the way contrast string are converted and multiple runs are handled here https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/glm/first_level/first_level.py#L572-L583 

However, when using `model.generate_report(contrasts=['contrast_str']*n_runs)` , the contrasts list are first converted to a dict of `{contrast_val:contrast_val}` here https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/reporting/glm_reporter.py#L196 and thus repetitions of contrasts are eliminated and the above hack cannot work.  


The simpler way would be to modify compute_contrasts by inverting the order of operation with first
https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/glm/first_level/first_level.py#L578-L583
 then https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/glm/first_level/first_level.py#L572-L578 

Unless I am not thinking about any caveat of doing it in that order (the only one that I can think of is performance of calling multiple time `expression_to_contrast_vector()` with the same parameters when runs have the same number of regressors).

**Comment by bthirion** [comment]
Thx for raising the point. I agree with the solution.
