### ISSUE TITLE
doc not building with sphinx 4.0.1

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2837]
`make html-noplot` fails since the latest release of sphinx on monday

see for example [this build](https://app.circleci.com/pipelines/github/nilearn/nilearn/2034/workflows/2bd1d45d-b513-41d2-a941-c17feab7e8e2/jobs/7212)

**Comment by emdupre** [comment]
I don't yet see an issue flagging this issue on `sphinx-copybutton` (https://github.com/executablebooks/sphinx-copybutton). It seems like an upstream problem there rather than a nilearn issue. Should we open an issue there directly ?

**Comment by RaphaelMeudec** [comment]
Or maybe you can try switching to `add_js_file` which has replaced `add_javascript` according to the doc : https://www.sphinx-doc.org/en/master/extdev/appapi.html?highlight=add_js_file#sphinx.application.Sphinx.add_js_file

**Comment by emdupre** [comment]
Thanks, @RaphaelMeudec ! That seems like a good solution.

In fact, despite the name, I realized that `sphinx_copybutton` and our `copybutton.js` share almost no overlap. `sphinx_copybutton` adds the ability to copy code blocks to the user's clipboard; for example, [here](https://7214-1235740-gh.circle-artifacts.com/0/dev/auto_examples/01_plotting/plot_visualize_megatrawls_netmats.html#fetching-the-megatrawls-network-matrices).

`copybutton.js`, meanwhile, only acts on code blocks starting with a `>>>` to hide or show the prompt and code output, like [here](http://nilearn.github.io/connectivity/functional_connectomes.html#a-functional-connectome-extracting-coordinates-of-regions). So they're largely non-overlapping in functionality, though I'm not sure what their interaction would be for those cells that are covered by `copybutton.js`.

Either way, I think the best patch to close this issue is just amending the call (exactly as you suggest). I still find `sphinx_copybutton` useful, so I won't close #2838 , but maybe we can continue discussion on its implementation there !
