### ISSUE TITLE
circleci cache

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2846]
@NicolasGensollen in the build that is currently running for this pr [here](https://app.circleci.com/pipelines/github/nilearn/nilearn/2085/workflows/47e3db27-18bd-49e2-901f-9b8d4e19177b/jobs/7263) none of the circleci caches are found; even though they exist and are found eg in [this one](https://app.circleci.com/pipelines/github/nilearn/nilearn/2085/workflows/47e3db27-18bd-49e2-901f-9b8d4e19177b/jobs/7263) 

do you see a reason why this is the case or does this mean the circle ci missed cache issue still exists?

**Comment by NicolasGensollen** [comment]
Thanks for opening this @jeromedockes !
I am not sure why circleCI sometimes misses the caches. I also noticed, that sometimes the cache isn't missed but is empty... It *could* be due to the fact that partial builds also run the save data cache step although they might have incomplete data folders. 
I'm wondering whether we should restrict this step to full builds only. :thinking: 
Doing conditional things in circleCI workflows is not super handy, but maybe we could have something like this at the end of the `build_docs` job:

```yaml
 - run: |
        if [[ "$(cat build.txt)" != "html-strict" ]]; then
                echo "Partial build : Not saving the data cache!";
                circleci-agent step halt
        fi
- save_data_cache
```

Such that only full builds execute the last step.
WDYT?

**Comment by jeromedockes** [comment]
> I am not sure why circleCI sometimes misses the caches.

I am afraid it could be the same issue that we tried to figure out together with circleci support but never could ...



> I'm wondering whether we should restrict this step to full builds only. thinking
> Doing conditional things in circleCI workflows is not super handy, but maybe we could have something like this at the end of the `build_docs` job:

yes I think so, only full builds should cache their data directory

**Comment by ymzayek** [comment]
Closing this as it's not relevant anymore after migrating the doc build to GitHub Actions and in any case it is handled in the new workflow
