### ISSUE TITLE
Glover HRF is not really Glover HRF?

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#2981]
Playing around with the HRFs I noticed that the Glover HRF in the GLM first_level does not actually correspond to the Glover 1999 canonical (auditory) HRF.
As these things go, it may be that I'm the one doing something wrong, so I'm opening this issue to ask whether someone else would be willing to double check my observation.

Here's a minimum working example:

```python
import numpy as np
from nilearn.glm.first_level import glover_hrf
import matplotlib.pyplot as plt

def original_glover(t, n1=6., t1=0.9, a2=0.35, n2=12., t2=0.9):
    """ As seen in Glover 1999, page 420. Using values for the auditory cortex (canonical Glover).
    Variables are named after those in the paper. 
    """
    gamma1 = t ** n1 * np.exp(-t / t1)
    gamma2 = t ** n2 * np.exp(-t / t2)
    
    c1 = gamma1.max()
    c2 = gamma2.max()

    return gamma1 / c1 - a2 * gamma2 / c2

# Let t represent time.
t = np.arange(0, 32, 0.02)  # 32 seconds, with a TR=1 and oversampling=50 (hence 0.02).

# Plot both HRFs normalized so we can compare their shape.
plt.plot(t, original_glover(t) / original_glover(t).max(), label="Glover 1999")
plt.plot(t, glover_hrf(1.) / glover_hrf(1.).max(), label="nilearn 0.8.1")
plt.legend()
```

Results in:
<img width="381" alt="Screen Shot 2021-09-22 at 23 42 41" src="https://user-images.githubusercontent.com/7881842/134451662-b0896f67-9dcb-4579-a1c9-af05cdcf881c.png">

Compare to the paper:

<img width="381" alt="Screen Shot 2021-09-22 at 23 55 27" src="https://user-images.githubusercontent.com/7881842/134452515-81e828e8-f7ff-4042-ba4e-2bc43e227c31.png">

At the end of the day this is not terribly worrisome, since both are decent HRF models and neither is "true", but I guess for reporting it'd make sense to fix this if it's a bug, or we could find a way to reproduce the plot in the paper given the currently implemented machinery?

Nilearn version:

### Expected behavior

Both functions would look the same.

### Actual behavior

The Nilearn hrf is slower and has a more subtle undershoot.

**Comment by bthirion** [comment]
Thx for opening the issue.
You're right: what has been missed in nilearn code are the c1 and c2 constants of Glover formula.
Would you mind opening a PR ?

**Comment by const7** [comment]
I'd love to fix it, but I've run into some problems.

The `glover_hrf` was implemented by the `_gamma_difference_hrf` function, which was used by several other hrf functions.
https://github.com/nilearn/nilearn/blob/cc11c85cd222632dcaf7c51005b549f75a49bbc4/nilearn/glm/first_level/hemodynamic_models.py#L103-L128

https://github.com/nilearn/nilearn/blob/cc11c85cd222632dcaf7c51005b549f75a49bbc4/nilearn/glm/first_level/hemodynamic_models.py#L18-L74

There are several solutions to fix this, like adding another parameter to `_gamma_difference_hrf` or directly implementing glover hrf within the `glover_hrf`, etc.

I assume it should be fixed with minimal modifications. But I'm not sure what kind of changes are acceptable and what is the most suitable solution. Could you give me some advice? Thank you! @bthirion

**Comment by NicolasGensollen** [comment]
Hi @const7 and thanks for looking into this ! 👍 
The `_gamma_difference_hrf` is a private function used in different places to factorize the code. Because it is private, we can modify it as long as we don't break backward compatibility for the public objects relying on it. This means that you could add parameters to `_gamma_difference_hrf` if you really need to, but it shouldn't change the default behavior for users. Typically the new parameter will have a default value yielding the exact same behavior as before.
That being said, I'm not sure to understand what new parameters you would need. Could you be more specific?

**Comment by const7** [comment]
> Hi @const7 and thanks for looking into this ! 👍 The `_gamma_difference_hrf` is a private function used in different places to factorize the code. Because it is private, we can modify it as long as we don't break backward compatibility for the public objects relying on it. This means that you could add parameters to `_gamma_difference_hrf` if you really need to, but it shouldn't change the default behavior for users. Typically the new parameter will have a default value yielding the exact same behavior as before. That being said, I'm not sure to understand what new parameters you would need. Could you be more specific?

Thanks for your quick reply!
I'm considering adding a `bool` parameter `is_glover` with default value `False` in `_gamma_difference_hrf` so we can fix the glover series without influencing other functions.

But I stuck into another problem that I'm confused about the passed parameters in `gamma.pdf` under `_gamma_difference_hrf`, especially why `dt` is included in (Sorry for any possible inconvenience since I'm new to this field).
https://github.com/nilearn/nilearn/blob/cc11c85cd222632dcaf7c51005b549f75a49bbc4/nilearn/glm/first_level/hemodynamic_models.py#L18-L74 

I cannot find an equivalent solution of canonical HRF (see below) based on the current `scipy.stats.gamma.pdf` idea. Do you have any suggestions? Thank you!
![image](https://user-images.githubusercontent.com/19154386/174270053-caed2a7f-ef9e-4323-b8ba-b7919ee62d7f.png)

**Comment by const7** [comment]
Thanks for your explanation! So the constants `c1` and `c2` are just used for the normalization of each gamma, right?

I'm still confused about two things:
1. What does the `hrf /= hrf.sum()` do in `_gamma_difference_hrf`, it's another form of normalization?
2. How to relate the actual gamma distribution with the above equivalent equation? It seems some terms in gamma pdf are dropped in the above equation. (sorry that I didn't find more information about it)

**Comment by bthirion** [comment]
1. It ensures that a one-unit input increase results in a one-unit bold response in the model, so that the beta coefficients in the glm can be correctly interpreted as percent of change of the signal wrt the baseline value.
2. These are gamma functions, not gamma distributions. the only relation is that gamma densities are gamma functions.  Note sure I interpret your question correctly.

**Comment by const7** [comment]
Thank you! Question 1 is fully answered.

Question 2, more specifically, I'm confused how things like `delay / dispersion` or `dt / dispersion` in `gamma.pdf` correspond to `n1`, `t1` in the above `y(t)` function.

How does `gamma.pdf` correspond to `c1 * t**n1 * np.exp(-t/t1)`? It seems that standard [`gamma.pdf`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html) have more complicated terms than gamma in the `y(t)` equation.

**Comment by bthirion** [comment]
`n1` corresponds to the so-called shape parameter and `t1` to the scale.

**Comment by const7** [comment]
I'm totally lost in the hrf calculation here
https://github.com/nilearn/nilearn/blob/cc11c85cd222632dcaf7c51005b549f75a49bbc4/nilearn/glm/first_level/hemodynamic_models.py#L68-L71

The parameter statement of `scipy.stats.gamma.pdf` is `pdf(x, a, loc=0, scale=1)`, and `a` is the shape parameter. So `delay / dispersion` and `dt / dispersion` correspond to `a` and `loc` respectively. It really wired.

Can you give some intuitions about it? I couldn't relate it to the mathematical gamma function at all. Thank you!

**Comment by bthirion** [comment]
Yes, there may be some more elegant way to parametrize the solution by taking `scale=dispersion`,  `shape=delay` and `loc=dt`, if I'm not mistaken. But that should amount to the same, right ?

**Comment by const7** [comment]
@dangom Thank you! I got almost the same result using this code compared with the original one.

@bthirion Sorry but I still couldn't understand why `dt` should be used here. 😢 (I know it represents the sampling interval.)

**Comment by bthirion** [comment]
Hm, this is a slight time shift (`loc` parameter). I'm not sure why it's here.
I guess it was to take care of a minor inaccuracy. but the effect is minor anyhow.

**Comment by const7** [comment]
Thank you.
It seems that we have to change the  `_gamma_difference_hrf` directly since we cannot get equivalent normalized gammas (things like `peak / peak.max()`) by passing different parameters.

**Comment by man-shu** [comment]
Correct me if I am wrong, but seems like this was fixed in #3295?

**Comment by Remi-Gau** [comment]
Reran the code in the top message and this is what I get. 

So things have improved.

![Figure_1](https://github.com/nilearn/nilearn/assets/6961185/abc5b8aa-3ac8-455b-9413-5429706fe85a)

**Comment by const7** [comment]
I've been puzzled by the differences and correspondences between the two implementations: one based on the formula definition and the other based on scipy's `gamma.pdf`. After reviewing the code and previous discussions, I realized that adjusting the `ratio` parameter when calling the `_gamma_difference_hrf` function can resolve the issue.

In `_gamma_difference_hrf`, the two gamma curves do not undergo normalization. Therefore, the new `ratio` value shoule be `old_ratio * peak_gamma.max() / undershoot_gamma.max()`, which is about `0.51`. However, due to differences between the `gamma.pdf` implementation and the formula-based approach, I made some manual adjustments and set the `ratio` to 0.48` to better align with the canonical Glover curve.

https://github.com/nilearn/nilearn/blob/860006beb7e0375e1b12bb895e8daf63bbb9808e/nilearn/glm/first_level/hemodynamic_models.py#L73-L81

https://github.com/nilearn/nilearn/blob/860006beb7e0375e1b12bb895e8daf63bbb9808e/nilearn/glm/first_level/hemodynamic_models.py#L135-L145

Here is the example code and plot:

```python
import numpy as np
from scipy.stats import gamma
from nilearn.glm.first_level import glover_hrf
from nilearn.glm.first_level.hemodynamic_models import _gamma_difference_hrf
import matplotlib.pyplot as plt


# Glover 1999
def original_glover(t, n1=6.0, t1=0.9, a2=0.35, n2=12.0, t2=0.9):
    """As seen in Glover 1999, page 420. Using values for the auditory cortex (canonical Glover).
    Variables are named after those in the paper.
    """
    gamma1 = t**n1 * np.exp(-t / t1)
    gamma2 = t**n2 * np.exp(-t / t2)
    c1 = gamma1.max()
    c2 = gamma2.max()
    return gamma1 / c1 - a2 * gamma2 / c2


# modify ratio parameter for glover_hrf
def glover_hrf_test(
    tr, oversampling=50, time_length=32.0, onset=0.0, ratio=0.35
):
    """
    Similar to nilearn.glm.first_level.glover_hrf, with `ratio` parameter.
    """
    return _gamma_difference_hrf(
        tr,
        oversampling,
        time_length,
        onset,
        delay=6,
        undershoot=12.0,
        dispersion=0.9,
        u_dispersion=0.9,
        ratio=ratio,
    )


# code from dangom
# https://github.com/nilearn/nilearn/issues/2981#issuecomment-1160515684
def sample_from_dangom(t: np.array):
    # Glover parameters
    peak_delay: float = 6.0
    peak_width: float = 0.9
    undershoot_delay: float = 12.0
    undershoot_width: float = 0.9
    positive_negative_ratio: float = 0.35

    peak = gamma.pdf(t, peak_delay / peak_width, loc=1 / 50, scale=peak_width)
    undershoot = gamma.pdf(
        t,
        undershoot_delay / undershoot_width,
        loc=0,
        scale=undershoot_width,
    )
    peak_norm = peak.max()
    undershoot_norm = undershoot.max()

    # gamma normalization
    hrf = (
        peak / peak_norm
        - undershoot / undershoot_norm * positive_negative_ratio
    )
    return hrf


# 32 seconds, with a TR=1 and oversampling=50 (hence 0.02).
t = np.arange(0, 32, 0.02)
plt.plot(t, original_glover(t) / original_glover(t).max(), label="Glover 1999")
plt.plot(
    t,
    glover_hrf(1) / glover_hrf(1).max(),
    label="ratio=0.35, current default glover_hrf",
)
plt.plot(
    t,
    glover_hrf_test(1, ratio=0.48) / glover_hrf_test(1, ratio=0.48).max(),
    label="ratio=0.48, fit to Glover 1999",
)
plt.plot(
    t,
    sample_from_dangom(t) / sample_from_dangom(t).max(),
    label="code from dangom",
)
plt.plot(
    t,
    glover_hrf_test(1, ratio=0.51) / glover_hrf_test(1, ratio=0.51).max(),
    label="ratio=0.51, fit to dangom code",
)
plt.grid(True)
plt.legend()
plt.show()
```

![image](https://github.com/nilearn/nilearn/assets/19154386/f3e770b4-0af6-4db7-94d5-b4d70fae2c2d)

I have submitted a new PR here #4452; please correct me if I am wrong.
