### ISSUE TITLE
LGTM.com recommendation: `masking._load_mask_img()`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nilearn/nilearn#2993]
### Expected behavior

See LGTM.com recommendation:
https://lgtm.com/projects/g/nilearn/nilearn/snapshot/b08a3f3e20dc2ff1608d8d556496ab56bbf3f63a/files/nilearn/input_data/nifti_labels_masker.py#xa8f5a03b806d5a87:1

Either remove the call to `masking._load_mask_img()`, or do not store the return values in variables (or add a `noqa` but unfortunately LGTM.com fails to interpret `noqa` correctly as can be seen in github/codeql#6528):
https://github.com/nilearn/nilearn/blob/60d6746671a36f7538ff59e23b0378253ccd8c10/nilearn/input_data/nifti_labels_masker.py#L370

Also, the documentation of `masking._load_mask_img()` should describe the second item of the returned pair **`mask, mask_img.affine`**:
https://github.com/nilearn/nilearn/blob/60d6746671a36f7538ff59e23b0378253ccd8c10/nilearn/masking.py#L42-L46

### Actual behavior

It's not clear why `masking._load_mask_img()` is called, if the resulting mask is not used. My guess is that the idea is to check the mask is valid (a `ValueError` is raised if it is not valid). If so, it would be nice to document that. Can you confirm?
https://github.com/nilearn/nilearn/blob/60d6746671a36f7538ff59e23b0378253ccd8c10/nilearn/masking.py#L30-L31

**Comment by NicolasGensollen** [comment]
Thanks for opening this @DimitriPapadopoulos 
I think you're right, `_load_mask_img` is "only" called in order to perform some checks making sure the mask is valid.
Since we don't need the return values, we can assign them to "_" or not assign them at all.
We can add a small comment but I don't think we need to add a lot of explanations since the docstring of `_load_mask_img` is already explicit enough:

https://github.com/nilearn/nilearn/blob/60d6746671a36f7538ff59e23b0378253ccd8c10/nilearn/masking.py#L30-L32

I agree that we should fix the return values in the docstring though, even if it is a private function.
