### ISSUE TITLE
`view_img` always masks `bg_img` with MNI mask

### ISSUE THREAD

**Issue by dbrennan44** [nilearn/nilearn#3120]
when plotting with view_img, it appears the bg image is being "masked" by a different brain (perhaps MNI?)
![image](https://user-images.githubusercontent.com/39420777/148601175-f7c93605-ff76-4cb2-813a-1a1cded3e611.png)

problem persists even when using same image as bg_image and plotted img

**Comment by bthirion** [comment]
Thx for reporting. Can you provide a  snippet of code (and possibly an image) to reproduce this ? Best,

**Comment by dbrennan44** [comment]
[malf_Labels.nii.gz](https://github.com/nilearn/nilearn/files/7831739/malf_Labels.nii.gz)

```
import nilearn as ni
from nilearn import image, plotting

malf=image.load_img('/Users/danielbrennan/Downloads/c001/malf_Labels.nii.gz')
plotting.view_img(malf,bg_img=malf,cmap="cold_hot",threshold="99%",black_bg=False)
```

**Comment by dbrennan44** [comment]
from messing around, it seems to be some kind of center-of-mass-like calculation which offsets the viewpoint. removing the `threshold="99%"` fixes the issue. But if I threshold outside of the plotting function, I get the same result

**Comment by bthirion** [comment]
Looking quickly at it, it seems to amount to the fact that `bg_img` is handled differently than `stat_map_img`: in particular it is not resampled. When these images are not in MNI space this indeed leads to spurious plots.
The point is that in most cases we have dealt with so far, the bg_img would  be an MNI template, or at least in MNI space.

**Comment by dbrennan44** [comment]
right, I'll see if I can change that behavior; I do most of my analysis in subject-space. Seems strange to allow supplying of bg_img but resample automatically into MNI.

Should also be emphasized again that this behavior goes away (i.e. plots correctly) when omitting the threshold argument

**Comment by NicolasGensollen** [comment]
@dbrennan44 `view_img` resamples the stat map to the background image automatically as can be seen here:

https://github.com/nilearn/nilearn/blob/78b09866b71c532552fd49e5cfd383db65b457b9/nilearn/plotting/html_stat_map.py#L535-L536

In addition, if you don't explicitely set `bg_img=False` in `view_img`, then the MNI152 template is used and the stat map is therefore resampled to the template. 

https://github.com/nilearn/nilearn/blob/78b09866b71c532552fd49e5cfd383db65b457b9/nilearn/plotting/html_stat_map.py#L444-L447

By setting `bg_img` to False, or to the stat map like you did, `view_img` shouldn't resample the stat map.

I'm not sure to understand why the threshold would change this though. It is only used to select the cut slices here:

https://github.com/nilearn/nilearn/blob/78b09866b71c532552fd49e5cfd383db65b457b9/nilearn/plotting/html_stat_map.py#L537

**Comment by jeromedockes** [comment]
- the bug is [here](https://github.com/nilearn/nilearn/blob/78b09866b71c532552fd49e5cfd383db65b457b9/nilearn/plotting/html_stat_map.py#L316); when preparing the "brain sprite" for the background a mask is computed (not sure why the background needs to be masked, in fact I don't think it should). the problem is that this is done with `compute_brain_mask` which just thresholds the mni152 template after resampling it to its first argument's resolution -- this doesn't work if the image isn't in mni space
- the problem also happens when there is no thresholding, but in that case we just don't see it because the background map is completely hidden behind the foreground map
- it is not a resampling issue, if the passed `bg_img` and stat map (as is the case here) have the same affine and shape the stat map isn't modified
- setting `bg_img=None` (or `False`) doesn't really solve the problem because (i) we do want the background image to be plotted and (ii) the masking of the background still happens so we see the outline of the mni template:

![Screenshot from 2022-01-10 10-34-42](https://user-images.githubusercontent.com/9196501/148793256-55637858-d372-4899-af52-afc0af6cc07b.png)

**Comment by jeromedockes** [comment]
During core dev meeting yesterday it was decided that:
- the default bg_img (MNI template) would continue to be masked, ie background is transparent outside of the brain
- any other background image will not be masked (so `black_bg` parameter may not be very useful in that case)
