### ISSUE TITLE
Links direct to the old version of documentation

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3163]
I am not sure how many cases are there, but I encounter some links are pointing to the old doc instead of the stable release doc.

### Affected pages
The one place I can think of is the [glossory](https://nilearn.github.io/stable/glossary.html#term-functional-connectome)
Not sure if there are pages that were systematically populated and share the same problem.

**Comment by NicolasGensollen** [comment]
Thanks for opening this @htwangtw !
I think we should do some cleaning of the repo `nilearn.github.io` such that it contains only `stable` and `dev` folders and a few other files at the root. Atm, I think that there are some artifacts of previous versions of the documentation at the root which cause the redirection to stable to not work as expected.
WDYT?

**Comment by NicolasGensollen** [comment]
>Sorry, I'm not sure I localize the problem properly.

@bthirion  If you go to the glossary, the link for "searchlight", for example, is `https://nilearn.github.io/decoding/searchlight.html`. When trying to access this page, you should automatically be redirected to `https://nilearn.github.io/stable/decoding/searchlight.html`, which is the link for the stable version of the docs. Currently this is not the case and I believe it is because we still have old folders and files on `https://github.com/nilearn/nilearn.github.io` (`decoding` folder in this example).
So I think the right "fix" would be to just clean the repo and not change the links in the docs.

**Comment by htwangtw** [comment]
Perhaps this one is good to be addressed in conjunction with #3122 ?
