### ISSUE TITLE
plot_carpet's cmap option doesn't work

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#3205]
carpet_plot does not respect cmap argument.

Nilearn version:

0.9.1dev

### Expected behavior
Passing cmap changes color of plot.

### Actual behavior
Plot is gray regardless of cmap value.

### Steps and code to reproduce bug

```python
from nilearn import datasets, plotting
import tempfile

data_spm = datasets.fetch_spm_auditory(
    data_dir=tempfile.mkdtemp(),
    data_name="spm_auditory",
    subject_id="sub001",
    verbose=1,
)
data = image.load_img(data_spm["func"])
plotting.plot_carpet(data, cmap="viridis")
```

**Comment by tsalo** [comment]
@dangom the `cmap` argument should only have an effect if an atlas is used (i.e., if `mask_img` is an atlas), since it only impacts the colorbar on the left side of the figure:

<img src="https://user-images.githubusercontent.com/8228902/161290743-e29829b8-bf68-46a4-8c13-7edade9c6fcb.png" width="300" />

This may be a documentation issue, rather than a bug. Or perhaps an opportunity for a new parameter, if you want to change the actual heatmap's colormap.
