### ISSUE TITLE
nilearn.interfaces.fmriprep.load_confounds - Allow users to specify confounds filename directly

### ISSUE THREAD

**Issue by ellisdg** [nilearn/nilearn#3273]
Allow users of nilearn.interfaces.fmriprep.load_confounds to specify the confounds filename (and associated metadata, if necessary) directly rather than requiring that the confounds filename be inferred from the fMRI filename.

### Benefits to the change
1. Allow users to be in control of the which confounds file is loaded.
2. The imaging file isn't necessary for loading the confounds.

### Pseudocode for the new behavior, if applicable

```python
load_confounds(confounds_filename=my_confounds_file, confounds_metadata=my_confounds_metadata_file, **kwargs)
```

I'm willing to take a stab at this if this request is approved.

**Comment by ellisdg** [comment]
Would it be possible to have a lower level function that loads the specified confounds file? The high-level function could still parse the image file and call the lower-level function.

If [_load_single](https://github.com/nilearn/nilearn/blob/7d04e2fa49030784c6ec5132f1f831de7c6540fd/nilearn/interfaces/fmriprep/load_confounds.py#L293) and [_confounds_to_df](https://github.com/nilearn/nilearn/blob/7d04e2fa49030784c6ec5132f1f831de7c6540fd/nilearn/interfaces/fmriprep/load_confounds_utils.py#L200) were refactored such that confounds file is derived from the image file first, and then a separate function is called to actually load the confounds, that would produce a function that could load the confounds file without needing to specify an image file.

My use case is that I use ‘init_bold_confs_wf’ from fmriprep in my own workflow. So my confounds file is the same as fmriprep. I want to be able to load the confounds within the same workflow without having to datasink the outputs fmriprep style and then load the confounds in a separate workflow.

**Comment by ellisdg** [comment]
That sounds good to me. Refactoring so that the functions are smaller has the additional benefit of making the code cleaner and more versatile.

**Comment by tsalo** [comment]
@htwangtw I would be okay supporting some low-level loading functions for BIDS-compatible derivatives. We should check the current status of the functional derivatives BEP to make sure that confounds files are fairly stable, but if we want to start handling generic confounds files, I think that should go in the BIDS interface module. That said, it should really be basic stuff, since `load_confounds` is what we want users using, when applicable.

**Comment by htwangtw** [comment]
Fantastic!
I would break down the task into two parts:
1. @ellisdg would refactor `_load_single` and `_confounds_to_df` to allow loading confound files. We will achieve this by completely isolate the file loading from the `_load_single` function.

2. Move the file retrieval code to the dedicated BIDS interface.

My gut feeling is, completing the refactoring proposed by @ellisdg, it will make the code easier to isolate that part of the code into the BIDS interface module suggested by @tsalo.

**Comment by tsalo** [comment]
@htwangtw I don't want to revive this, but before I open an issue about loading AROMA confounds, I want to double-check that I understand things. AFAICT, AROMA confounds should be available in the confounds tsv, so does `load_confounds` actually need the `desc-smoothAROMAnonaggr_bold` file?

**Comment by htwangtw** [comment]
Lots to unpack here

> AFAICT, AROMA confounds should be available in the confounds tsv

They are their for record keeping.
Under normal circumstances you should **not** use them.
There is, however, away to load the with the load_confounds API at one point of the development. We now make it either really inconvenient or just didn't allow that to happen because it's not how the original software intended to denoise.

> so does `load_confounds` actually need the `desc-smoothAROMAnonaggr_bold` file?

ICA AROMA is the major reason why we force the users to pass the image file rather than the confound file. 
The correct implementation of ICA-AROMA must be performed on `desc-smoothAROMAnonaggr_bold`. 
This is a deliberate inconvenience to force the user to understand ICA-AROMA if they wish to use it. 

In this file the aroma regressors have already been handled with a different way in the original software. 

Directly quoting fMRIprep doc:

>If you are already using AROMA-cleaned data (~desc-smoothAROMAnonaggr_bold.nii.gz), do not include ICA-AROMA confounds during your design specification or denoising procedure.

Regressing out aroma regressors from the regular output is not only not recommended. In the original paper it was used as a case to compare performance with the formal implementation in the final software.

In the current doc we provided some explanation without overloading users with too much details. If there's a better way to rework it I am happy to see the suggestion.

**Comment by tsalo** [comment]
Oh... I think I understand now. So you're saying that we can't just use the AROMA noise components if we want to do non-aggressive denoising (which is generally a better choice than aggressive denoising)? That makes sense to me.

It seems like the only alternative would be to load the MELODIC mixing matrix, separate it into noise and signal components, and orthogonalize the noise components w.r.t. the signal components before including them in the design specification (when targeting the regular BOLD data).
