### ISSUE TITLE
Test error in scipy `1.9.0rc1`

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3288]
The test is currently failing with scipy `1.9.0rc1`: See [here](https://github.com/nilearn/nilearn/runs/7067861378?check_suite_focus=true) for example. The failing test is:

https://github.com/nilearn/nilearn/blob/4242c0d03e3fc790b17a1d88ce5a4140633c6b6f/nilearn/decoding/tests/test_decoder.py#L435-L440

failing with error:

```
if Wn.size > 1 and not Wn[0] < Wn[1]:
>           raise ValueError("Wn[0] must be less than Wn[1]")
E           ValueError: Wn[0] must be less than Wn[1]
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/scipy/signal/_filter_design.py:2468: ValueError
```

The error is due to this check which was added in this PR: https://github.com/scipy/scipy/pull/15886
See also the related issue: https://github.com/scipy/scipy/issues/15773.

**Comment by ymzayek** [comment]
@NicolasGensollen thanks for tracing this. I can open a PR to fix it unless you're already working on it. I see that it is due to the function `signal._check_wn` setting 'critical_frequencies' to be equal when `wn` is more than or equal to 1. With the scipy update this does not hold anymore. A simple fix is to add the following after https://github.com/nilearn/nilearn/blob/2ac57f2c42aff83472edb9adeb13d5f0f30d611a/nilearn/signal.py#L263

```python
        if btype == 'low':
            wn += 10e-16
```

**Comment by bthirion** [comment]
Yes, let's enforce it numerically whenever it's needed.
Thx for noticing !
