### ISSUE TITLE
design matrix columns name checking is excessive

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3323]
Currently, a string can only a design matrix column if it fits the  `isidentifier()` condition, which looks excessive.
For instance, strings started with a number are not accepted, while there is no problem to create dataframes with such strings.
Thus I suggest to remove the lines below from the codebase

https://github.com/nilearn/nilearn/blob/2fd96b86cb53304f2f0b0c978d0bcd670f3795d2/nilearn/glm/first_level/hemodynamic_models.py#L443
```
# Check that all names look like proper pandas.DataFrame column names
    if not all([name.isidentifier() for name in names]):
        raise ValueError("At least one regressor name can't be used "
                         f"as a column identifier: {names}")
```
WDYT ?

**Comment by ymzayek** [comment]
Thanks for raising @bthirion but I think that is there in order to allow access to columns as attributes (using such syntax as `df.A`). This does not work with invalid identifiers (which you can only access using `[]` syntax). For more details see this section and relevant warning block in pandas docs: https://pandas.pydata.org/docs/user_guide/indexing.html#attribute-access. We could of course remove that and let the user deal with pandas error.

**Comment by jeromedockes** [comment]
It's perfectly fine and quite common to have pandas column names that are not
valid identifiers and it's better to always index dataframes with `[]` (or
`loc`, `iloc`, `at`) anyway.

In any case, the function chooses the names so if they are not satisfying it
should make a different choice (as it already tries to do by removing spaces,
non-ascii and non-word characters) rather than fail and complain to the user
about its own error. BTW the same applies to making sure the names are all
different.

**Comment by bthirion** [comment]
Thx ! I had the concrete case of a column name starting with a digit. What would be the replacement in that case ?

**Comment by jeromedockes** [comment]
IMO the best is to do what you suggest in your first comment -- keep the original name, ie have a column name in the design matrix that is not a valid identifier, and access it with standard indexing eg `design_matrix["1): my name"]`.

but if we do want to go for transforming it in a valid identifier we could prefix it with some arbitrary string that starts with a letter, eg `reg_1_my_name`.

**Comment by ymzayek** [comment]
> IMO the best is to do what you suggest in your first comment -- keep the original name, ie have a column name in the design matrix that is not a valid identifier, and access it with standard indexing eg `design_matrix["1): my name"]`.

I'm ok with this. An error raised relating to the indexing I mentioned is a non nilearn issue anyways.
