### ISSUE TITLE
Misleading name for plot_epi function 

### ISSUE THREAD

**Issue by philouc** [nilearn/nilearn#3388]
There is no specific reason to name the `plot_epi` function as such even though most k-space encoding schemes in fMRI
rely on Echo Planar Imaging. We're working on 3D SPARKLING k-space encoding schemes for fMRI and would like
to use this function too. Of course it's totally doable as this function is independent of the way k-space data has been
collected. Consequently we suggest renaming this function `plot_fmri` to make it usable with other encoding patterns.

### Benefits to the change
Doing so, users would be aware that is function just allows them to plot an fMRI image (for instance the mean of an fMRI sequence)
To preserve backward compatibility I suggest creating an alias to the existing `plot_epi` function

### Pseudocode for the new behavior, if applicable

```python
from nilearn.plotting import plot_fmri
plot_fmri(mean_clock_retino, colorbar=True, cbar_tick_format="%i")
```

**Comment by bthirion** [comment]
I think that we originally used  `plot_epi` because it would be usable for data such as field maps, diffusion-weighted maps etc. But it is fair to say that this is probably mostly used for fMRI.
What do people think about the change ?

**Comment by tsalo** [comment]
I think we could probably make it more generic than `plot_fmri` in that case. What is the broadest description of the function? Is it useful for _any_ low-resolution 3D niimg?

**Comment by alexisthual** [comment]
I just discovered this method today because someone else used it in front of me. I personally would not have guessed that I could use `plot_epi()` to plot an fMRI image (this is what we did in this case).
In my opinion, `plot_cuts()` or `plot_slices()` would describe well what it to be expected from this method :slightly_smiling_face:

**Comment by alexisthual** [comment]
Yes that's true... The difference between `plot_anat` and `plot_epi` is not clear to me at this stage.

**Comment by bthirion** [comment]
These functions simply have different defaults for easy vizualisation.

**Comment by bthirion** [comment]
The original suggestion of adding `plot_fmri` as an alias to `plot_epi` is maybe the best suggestion we have so far ?

**Comment by emdupre** [comment]
> unless someone has a strong opinion about it.

I know I'm very late to this discussion, but I am a little nervous about moving to `plot_fmri` as there are lots of developments in this space (see e.g. [VASO fMRI](https://layerfmri.com/2020/01/02/vasoworldwide/)) that we (presumably) have no plans to support. EPI, though, is an older and well-established imaging sequence, so we have more expectations of what the images will look like and what the plots depict.

Essentially, I see `plot_epi` function as plotting a particular class of images rather than for plotting a given acquisition method. If we want to move to the latter, as `plot_fmri` would suggest, I think we'll need to be more aware of ongoing updates in that space.

**Comment by bthirion** [comment]
Sorry, I don't know about Vaso. You mean that if we can't call this function on a vaso image ?

**Comment by emdupre** [comment]
> You mean that if we can't call this function on a vaso image ?

Yes, that's my general concern. I _think_ we can plot vaso images (though I haven't tried !), but there are many other fMRI sequences coming out; e.g. 3D-GRASE. I'd worry that we'll be more likely to reach a point where we can't use this function to plot something that is an actively used fMRI sequence ; I'm not tracking that space very closely, so I'm not sure how likely that is to occur soon. But it seems like a worry that's only introduced by this change and wouldn't be present with `plot_epi`

**Comment by emdupre** [comment]
I know this is in tension with your initial concern, @philouc ! I suppose I'm just asking whether if we say that this can be used to plot any fMRI image &mdash; there are more and more sequences that qualify as fMRI &mdash; are we more likely to see variability in how we best represent all of these sequences ? If so, that seems like a harder problem to solve than staking our plotting to a single kind of (popular) sequence, and allowing users to re-use it for compatible acquisitions.

**Comment by ymzayek** [comment]
@emdupre thanks for bringing this up. I have neglected working on the linked PR a bit so it's good to rethink it at this point and I understand your concern. We can also try to think of another name for the function that generalizes away from the type of acquisition or image class but makes it easier for people to understand what the function can be used for. There were already some other suggestions above.

**Comment by ymzayek** [comment]
After a discussion about this at the last developer meeting, we decided that there isn't a strong reason to change the name of the `plot_epi` function and at the moment there are no better alternatives. I will go ahead with closing this issue and the linked PR.
