### ISSUE TITLE
resample_target="data" in NiftiMapsMasker/NiftiLabelsMasker

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#340]
NiftiMapsMasker/NiftiLabelsMasker need to accept resample_target="data" (to avoid blowing up the memory when Atlas is oversampled as in the yeo_2011 case)

**Comment by AlexandreAbraham** [comment]
This is not as easy as it seems. In fact, it brings inconsistencies to the masker as the affine is defined in the transform rather than the fit. For example:
```python
masker = NiftiLabelsMasker(labels_img, resample_target='data')
masker.fit()

# First dataset, target_affine is set to affine_data_1
data1 = masker.transform(dataset1)

# Second dataset, target_affine is set to affine_data_2
data2 = masker.transform(dataset2)

# Inverse transform, my data has been resampled into dataset2 space
masker.inverse_transform(data1)
```
We could say that the affine is defined on the first transform, but I find this misleading. We could also say that the `target_affine` is defined by the data given in the `fit` but it would conflict with mask computation and also be misleading compared to the behavior of the classical NiftiMasker.

I would be more in favor of accepting niimgs in the `resample_target` parameter.

**Comment by GaelVaroquaux** [comment]
> I would be more in favor of accepting niimgs in the resample_target parameter.

I am not that much in favor of that, because it makes it really hard to
have a sane default.

Could we have that, at transform time, we store a resampled_altas_ (or
other name) attribute that is the resampled atlas (if resampling is
required, and the original atlas if there is no need for resampling).

If new data comes along (as in a new call to transform), the atlas would
be resampled from the original atlas image if it is not on the right
affine.

I realize that this makes parallel computing in the transform nasty. I am
not sure how nasty though. We probably will have to put some resampling
logic in the signal extraction routine that is used in parallel. I think
a design like passing the original atlas niimg and the resampled one to
the function called inside the parallel loop. The function would return
the resampled atlas, and we would store the last one of the for loop.
This would mean that in parallel computing, the atlas would probably get
resampled multiple unecessary times, however caching would limit the
number of times this happens.

I believe that this is important, because it opens the door to a
resample_target='auto' where the smallest of both resampling is taken.
For end users, this would be a 'just work' settings, while the current
setting leads to memory explosions. For non advanced users, this is a
blocker, as they do not know how to debug (and worst case, they can crash
their computer).

**Comment by AlexandreAbraham** [comment]
> If new data comes along (as in a new call to transform), the atlas would be resampled from the original atlas image if it is not on the right affine.

The problem is not the `transform` step, it is the `inverse_transform`. If resampling is done on heterogenous data, how do we chose the affine when `inverse_transforming`? For me, it is better to explicitely give an affine (or a niimg which has the desired affine).

> I realize that this makes parallel computing in the transform nasty.

I think we can consider resampling the atlas as costless. Given that masking is usually done once and cached, it doesn't bother me if there is a small overhead per process.

**Comment by GaelVaroquaux** [comment]
> The problem is not the transform step, it is the inverse_transform. If
> resampling is done on heterogenous data, how do we chose the affine when
> inverse_transforming?

Good point indeed. We can specify that the inverse transform always
return the data in the space of the atlas unless an explicit affine is
passed. These are consitent semantics (in the sens that they offer little
surprises). They may lead to memory explosions, but note that
inverse_transform will be used by much less people than transform (it is
a less common case). Also, the memory explosion is more obvious because
it occurs via the size of the output created by the function. In the
current case, it is harder to guess, as it occurs in an intermediate
variable.

**Comment by AlexandreAbraham** [comment]
OK, I see your point now. In my head, I thought that what you are describing was the default behavior of NiftiLabelsMasker. I think that it should actually be the default behavior and not requiring a `resample_data='data'` (which, semantically, has also no sense :P). I suggest that we talk about that during a coffee break otherwise it will take ages to reach a conclusion ;).

**Comment by GaelVaroquaux** [comment]
> I suggest that we talk about that during a coffee break otherwise it
> will take ages to reach a conclusion ;).

OK. I am at neurospin tomorrow.

**Comment by AlexandreAbraham** [comment]
While I'm on nilearn issues list, let's take a decision on this one: I agree with you that we should have a `resample_target='data'` and that this should be the default behavior.

PR welcome! It shouldn't be too long.

**Comment by GaelVaroquaux** [comment]
Fixed!
