### ISSUE TITLE
Improve cuts in nilearn.reporting.make_glm_report

### ISSUE THREAD

**Issue by AudreyDuran** [nilearn/nilearn#3442]
[`make_glm_report`](https://nilearn.github.io/dev/modules/generated/nilearn.reporting.make_glm_report.html) does not allow to choose the coords of the cuts we want, on the contrary to [`plot_stat_map`](https://nilearn.github.io/dev/modules/generated/nilearn.plotting.plot_stat_map.html) method. 

In addition, defaults cut are not the same for the mask and the computed statistical map. 

Also, when there is nothing significant, the default cuts don't cover the whole brain but only a small part (non uniformly distributed).

![image](https://user-images.githubusercontent.com/9747190/205360003-9a33a481-95cf-48f6-90f3-f8ebc956cb55.png)
![image](https://user-images.githubusercontent.com/9747190/205359771-74d4e076-c52f-4dee-aacb-068e0f998b44.png)

### Benefits to the change

User-friendly and easy to perform changes I guess.

**Comment by emdupre** [comment]
Hi @AudreyDuran,

Thanks for this suggestion ! Since `make_glm_report` is [calling `plot_stat_map` internally](https://github.com/nilearn/nilearn/blob/ffc0489b19b01b3231862846fc15ef72cfdbd249/nilearn/reporting/glm_reporter.py#L909-L913), we should be able to set coordinates appropriately by creating a new argument for `make_glm_report` and passing it through.

Do you want to open a pull request for this ?
