### ISSUE TITLE
Enable test coverage reporting in Travis

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#360]
@lesteve recommended this here: https://github.com/nilearn/nilearn/pull/359#discussion_r23238825 , and I agree!

We should see how this is being accomplished in `scikit-learn`, and try for something similar.

**Comment by lesteve** [comment]
Great you tackled that. It seems that you need to run coveralls in the after_success travis step.

Also I seem to remember that scikit-learn only uses coveralls for one of their build in the build matrix (see their [.travis.yml](https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml). I am wondering whether you get plenty of redundant message otherwise if you do it for each build.
