### ISSUE TITLE
Plotting: Respect red–green color blindness in colormap choices

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#365]
It may sound trivial, but an increasing number of neuroscience journals strongly discourage simultaneous use of green and red colors for distinctions in article figures.

This is why wanting to use more than 2 different colors with nilearn-provided colormaps may currently not be easy, at times.

Suggestion: perhaps one or two more "standard" colors could to added

**Comment by GaelVaroquaux** [comment]
I agree with you. However, for most of our default colormaps this is
already the case, so I am not sure what we can do more.

**Comment by banilo** [comment]
For example, one or two more "transparent" flavors could be added. Currently, I only find:
```
nilearn_cm.blue_transparent
nilearn_cm.green_transparent
nilearn_cm.red_transparent
```

**Comment by GaelVaroquaux** [comment]
> For example, one or two more "transparent" flavors could be added.
> Currently, I only find:

You want also the cmy flavor corresponding to the rgb ones? Fine with me,
it's just a PR away :).

**Comment by banilo** [comment]
It's kinda surprising, but almost 10% of men are red-green blind and 0,5% of women. So, 1 out of 20 plot viewers/paper readers will not be able to tell red and green aspects apart. In fact, this twentieth person might be one of your reviewers ;-)

**Comment by lesteve** [comment]
If you really want to do that, just go there https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/cm.py#L170 and add your favourite color.

Something I would say: transparent color map rendering is not great and that's the reason we dropped them from the glass brain if you remember.

**Comment by AlexandreAbraham** [comment]
CMY is for printing, I don't see the relation with color blindness (yellow especially is bad for a colormap).

In order to show several things in the same plot, I made some code to take *n* colors from any colormap and create a "transparent to color" colormap. Typically, if you apply that to 3 fuzzy brain maps with the spectral colormap, it will take the first, the last and the middle color of spectral, build 3 colormaps different from them, and overlay the 3 brain maps on one figure.

I know that it won't solve the color blindness problem, but if you think that (part of) this code can be useful here, it is just 2 clicks away ;).
