### ISSUE TITLE
Make sure tests do not create non temporary files

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3714]
btw I noticed the "created during testing" section of the gitignore; even better would be not to create files outside of pytests' tmp folder in tests. examples should also probably avoid writing files, or clean them up

_Originally posted by @jeromedockes in https://github.com/nilearn/nilearn/issues/3712#issuecomment-1516409516_

**Comment by Remi-Gau** [comment]
I think I am the one responsible for adding some of those entries in the gitignore.

IIRC the extra files created are due to this test: https://github.com/nilearn/nilearn/blob/199b8606adb6df78020089b569c795d060ac4a0e/nilearn/glm/tests/test_second_level.py#L290

Where the temp dir with the context manager was commented out.

I tried uncommenting the code in this file in one past PR but it lead to failures in CI on windows.

**Comment by jeromedockes** [comment]
I'd have to see the error message to be sure but that sounds like there is an open file handle for a file in that directory, so the OS refuses to remove it. it could be due for example to a memory map in a Nifti1File object

**Comment by Remi-Gau** [comment]
the log is not available anymore but here is where I attempted to fix it.
https://github.com/nilearn/nilearn/pull/3600#issuecomment-1475195749

**Comment by Remi-Gau** [comment]
closed by #3716
