### ISSUE TITLE
[DOC] mention latex requirement for building docs in "Contributing" page

### ISSUE THREAD

**Issue by psadil** [nilearn/nilearn#3852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The Maintenance page points to a few latex requirements (https://nilearn.github.io/dev/maintenance.html#build-and-deploy-the-documentation), but not the Contributing page. That can be fine, but it led to an error that confused me while trying to build the docs via `html-noplot`. Specifically, that command uses the flag `-W` which turns warnings into errors. Without latex, I get this warning (which breaks `html-noplot`)

```
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the imgmath_latex setting
```

### List any pages that would be impacted.

Contributing, section Build and deploy the documentation (https://github.com/nilearn/nilearn/blob/main/CONTRIBUTING.rst)

**Comment by ymzayek** [comment]
Since adding warnings-as-failures on the partial build, `make html-noplot` will fail without the latex dependencies but this is not related to adding new code. One suggestion in order not to add a dependency for contributors we could make a separate partial build command that is used in the CI where the dependencies will be installed and revert `make html-noplot` to old behavior. The other option is to find the right latex distributions to add to our doc requirements in `pyproject.toml` so that they are easily installed by an environment manager. Either way would avoid pointing contributors to the maintenance docs.

**Comment by bthirion** [comment]
I think I prefer the first option (dedicated CI). To be discussed.
