### ISSUE TITLE
[BUG] In plot_to_surf vmin is set to 0 despite not setting a threshold

### ISSUE THREAD

**Issue by eurunuela** [nilearn/nilearn#3944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

Mac OS Version 13.4.1 "Ventura"

### Python version

- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [X] 3.8
- [ ] 3.7

### nilearn version

Dev version in #3942 

### Expected behavior

The minimum value in the colorbar should be set by `vmin` when the user does not provide a `threshold`.

### Current behavior & error messages

This is what I got:

```python
# Paste the error message here
UserWarning:

choosing both vmin and a threshold is not allowed; setting vmin to 0
```

I assume `threshold` has a numerical value by default (rather than `None`) and that's why `vmin` is set to 0.

### Steps and code to reproduce bug

```python
# Paste your code here
cmap = hm_viridis_onesided
# cmap = "viridis"
vmax = 4
# vmin = vmax/data.shape[1] * 60
vmin = 2
event_count = masker.transform(op.join(out_dir, "data_event_count_avg.nii.gz"))
event_count = np.squeeze(event_count)


texture = vol_to_surf(utils.color_rois(out_dir, mask, event_count), fsaverage.pial_left,interpolation='nearest',radius =1, n_samples=1)
surf_plot1=plotting.plot_surf_roi(fsaverage.infl_left, texture, hemi='left', cmap = cmap, colorbar=True, vmin = vmin, vmax = vmax, bg_map=fsaverage.sulc_left, engine="plotly")
```

**Comment by bthirion** [comment]
Thx for reporting.
This probably a side effect of making vmin explicit, which was not done in the original implementation.

**Comment by ymzayek** [comment]
It looks like a bug for the plotly engine. Works as it should for matplotlib. Here's a code to more quickly reproduce the warning and buggy behaviorr:

```python
from nilearn import datasets
from nilearn import plotting

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas['map_left']

fsaverage = datasets.fetch_surf_fsaverage()
plot_1 = plotting.plot_surf_roi(
            fsaverage.infl_left,
            parcellation,
            hemi="left",
            cmap="viridis_r",
            vmin=2,
            vmax=50,
            colorbar=True,
            bg_map=fsaverage.sulc_left,
            engine="plotly",
         )
plot_1.show()
```

I'll follow up with a PR to fix

**Comment by ymzayek** [comment]
Looking more into it, would it be better to allow both vmin and threshold to be passed to mimic matplotlib behavior?

Allowing this would change the behavior of js_plotting_utils.colorscale function where the vmin returned would be changed leading to a change in how the colorbar looks and the data scaling in the plot (to be the same as matplotlib).

As it is, the warning will always be raised unless the user defines threshold=None because by default it is given a float. If we want to keep the current behavior then the warning should say that the user needs to set threshold=None if they want to use vmin. And we'd also need to move a few lines under plot_surf_roi that automatically set vmin if it is not specified by the user.

I think the first option is preferable especially if we consider this a bug and behavior should look like matplotlib.

Old behavior with warning with vmin set to 10 and threshold set to 20:
![newplot](https://github.com/nilearn/nilearn/assets/63292494/8e8ef672-b2a9-4adf-bc57-40ee8b9d1c50)

New behavior WITHOUT warning with vmin set to 10 and threshold set to 20:
![new](https://github.com/nilearn/nilearn/assets/63292494/0c435298-41db-4ebb-9609-4a4a3d58ca93)


With the second option the plot would be the same as the first but the warning would change.

**Comment by bthirion** [comment]
Looks good. We should make sure that the behavior is consistent btw mpl and plotly.
