### ISSUE TITLE
plot_surf_roi should raise error when negative or floating-point values are passed

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#4104]
plot_surf_roi is for showing atlas region indices, so it is meant to deal with positive integers only.
we should probably raise an error when negative or floating-point values are passed to this function

_Originally posted by @jeromedockes in https://github.com/nilearn/nilearn/issues/4082#issuecomment-1787355353_

**Comment by jeromedockes** [comment]
> _Originally posted by @jeromedockes in https://github.com/nilearn/nilearn/issues/4082#issuecomment-1787355353_

oops sorry Yasmin we said that I would open an issue and I didn't! thanks for taking care of it :)

**Comment by ymzayek** [comment]
No problem :)

**Comment by michellewang** [comment]
I can take this one if no one is working on it right now

**Comment by michellewang** [comment]
It turns out that some of the existing tests will fail if we force `roi_map` to only have integer values, because they try to plot a dummy parcellation made up of floats:
https://github.com/nilearn/nilearn/blob/d53ba5830207546744fdda3071f55620ea946b8d/nilearn/plotting/tests/test_surf_plotting.py#L724-L728

With the test data generated by this function (see Line 710):
https://github.com/nilearn/nilearn/blob/d53ba5830207546744fdda3071f55620ea946b8d/nilearn/plotting/tests/test_surf_plotting.py#L705-L711

Should `parcellation` instead be random integers? Or should we relax the new constraints to allow float values?

**Comment by bthirion** [comment]
Sorry, I don't get your point ? The above example runs correctly ?

**Comment by michellewang** [comment]
@bthirion yes the test case runs with the current version of the code, but it fails if I update the code to throw an error if the `roi_map` has floats (which is what this issue is asking for). So I am trying to clarify whether we do want to allow floats or not. 
* If we want to allow floats, then the new PR I am working on will only add the error behaviour when `roi_map` has negative values
* If we do not want to allow floats, then some of the existing tests will need to be modified to not have floats
  * From my understanding, it is more common for parcellations to have integer values instead of floats, so I think this option would make sense. But I have not worked that much with parcellations before so I could be wrong. It would also depend on how much we would want to constrain user inputs here

**Comment by bthirion** [comment]
Thx for clarifying. I prefer option 2: forbid floats in parcellations.

**Comment by ymzayek** [comment]
I think it's ok to restrict to integer values but this might break user code so we might want to think about whether we want to make the change with a deprecation cycle. Given that it is rare to have parcellations with floats I don't think it's a big deal
