### ISSUE TITLE
Documentation requires sklearn.__version__ > 0.14.1

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#424]
The following commands  (section 2.1.2.2.2. Choosing a good cross-validation strategy) do not work with sklearn 0.14.1
>>> from sklearn.cross_validation import permutation_test_score
>>> null_cv_scores = permutation_test_score(svc, fmri_masked, target, cv=cv)

**Comment by alpinho** [comment]
Also: in section 2.1.3.1. Dimension reduction with feature selection
X and y are undefined

**Comment by alpinho** [comment]
section 2.1.4 n_conditions is not defined

**Comment by alpinho** [comment]
same section
>>> rfe_svc = Pipeline([('rfe', rfe), ('svc', clf)])
clf is actually svc

**Comment by lesteve** [comment]
Thanks for your report, posting the errors traceback would be helpful as would a link to the documentation section you are referring to.

Because part of the documentation snippets are from examples scripts in examples and part of the other snippets are directly in the rst files (the one starting with the python promts `>>>`) it may well be the case that there is some mismatch between the two.

Of course PR are more than welcome on this documentation issues.

**Comment by AlexandreAbraham** [comment]
Does the new doc solve these problems?

**Comment by lesteve** [comment]
> Does the new doc solve these problems?

My guess: probably not although I haven't checked. I think the emphasis was more on restructuring than fixing bugs.
