### ISSUE TITLE
[DISCUSSION] Align Nilearn to scientific-python SPEC 0

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4425]
Opening an issue to see how maintainers / users feel about slowly trying to align Nilearn to the Scientific Python ECosystem - 0  recommendations regarding reducing the scope of supported dependencies versions.

https://scientific-python.org/specs/spec-0000/

The motivation (see below) seems attractive for maintainers but I would like to know how users or maintainers of downstream packages may feel about this.

> Limiting the scope of supported dependencies is an effective way for packages to limit maintenance burden.

**Comment by jdkent** [comment]
I'm okay with this, @emdupre, you may represent another camp to support more versions of matplotlib?

**Comment by emdupre** [comment]
Thanks for the ping, @jdkent !

We've generally been quite a bit more conservative than these guidelines would suggest. I'm also hesitant to change that conservatism, as it would move us out-of-sync with scikit-learn. Currently, scikit-learn has the following [required dependencies](https://github.com/scikit-learn/scikit-learn/blob/99916c40d1f145d75a3393c8d6357593c2b0a486/pyproject.toml#L9-L14) :

```
dependencies = [
  "numpy>=1.19.5",
  "scipy>=1.6.0",
  "joblib>=1.2.0",
  "threadpoolctl>=3.1.0",
]
```

and their MPL dependency, [though optional](https://github.com/scikit-learn/scikit-learn/blob/99916c40d1f145d75a3393c8d6357593c2b0a486/pyproject.toml#L49-L69), is also more closely aligned to our current versioning than to these guidelines :

```
docs = [
    "matplotlib>=3.3.4",
    "scikit-image>=0.17.2",
    "pandas>=1.1.5",
    "seaborn>=0.9.0",
...
```

Since nilearn is intended to interact quite closely with scikit-learn, it would seem odd to me if they systematically supported older versions than we did. So, I'm personally -1 to this proposal.

**Comment by Remi-Gau** [comment]
> Sticking to sklearn is indeed our historical choice.

I am actually not sure I understand the reasoning.

If the sklearn team does not want to update their dependencies, it is fine. But why do we have to align with their policy?

Saying that we have been conservative with updating dependencies so we will stick to this approach requires to justify why we should be conservative in the first place. What do we gain (or lose) by doing so? I am way newer to the Nilearn project so I suspect that @bthirion or @emdupre may know more about the rationale.

As long as the dependencies we support are a subset of those supported by sklearn, I do not think we can be "out of synch".

**Comment by bthirion** [comment]
My view is that we want to minimize constraints on users. The point is that people who use Nilearn hopefully use a bunch of other Python libraries, and we don't want to put them in the difficult situation where they have to deal with incompatibilities in the dependencies: this calls for conservativeness.
I have to say that my experience with many packages that are on the bleeding edge is that it's very hard to have them run smoothly. AFAICT it's not the case for Nilearn, partly due to our past choice.
It may  be that sklearn is a bit extreme, because they expect their users to work in very constrained environments. But it may be the case for our users too (public compute clusters typically evolve slowly).

**Comment by emdupre** [comment]
Just pinging that this relates to #4419, since it's not explicitly linked above.

**Comment by Remi-Gau** [comment]
Will also close this one.

For now let's go with a "bump dependency versions when some "features" we rely on gets deprecated".
