### ISSUE TITLE
[DOC] Cingulate regions labeled as cingulum in fetched AAL atlas

### ISSUE THREAD

**Issue by JLefortBesnard** [nilearn/nilearn#4551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Hi Nilearn team :wave:
The fetched AAL atlas is version 2 from 2015 (see [datasets/atlas.py](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py#L1300-L1309)), while the current [AAL version 3 dates from 2019 with recent updates](https://www.gin.cnrs.fr/en/tools/aal/). We noticed this because AAL2 labels cingulate regions as 'cingulum'; I'm not sure if terminology has changed, but now '[cingulum](https://en.wikipedia.org/wiki/Cingulum_%28brain%29)' is universally understood as the large white matter track and *not* a gray matter region.
Would it be feasible to update the Nilearn atlas to reflect the latest AAL3 labeling?

**Comment by Remi-Gau** [comment]
The fetcher already has a version parameter: we could add "AAL 3v2" to fetch the latest version.

Is that what you are asking?

**Comment by JLefortBesnard** [comment]
If it's not too much trouble, I believe it could be helpful. What do you think? 
By the way, I'm happy to help!

**Comment by Remi-Gau** [comment]
I think it should not add too much code and maintenance work, so I would suggest to try it.
Feel free to open a pull request.

**Comment by JLefortBesnard** [comment]
The AAL 3v2 includes 166 parcellations rather than the previous 117 + the indices are now consecutive integers from 0 to 166 (with a [few exceptions](https://www.gin.cnrs.fr/wp-content/uploads/AAL3_UserGuide_April2024.pdf)). This means the current documentation is not accurate for the 3v2 atlas.
I'm unsure about the next steps. Should I make "SPM 12 3v2" the default and update the documentation, or should I retain "SPM12" as the default and include a specific paragraph about 3v2? Or something else?

**Comment by Remi-Gau** [comment]
I woukd keep the SPM12 as the current default but start throwing a warning so that when people use the current default they are told that this default will change to aal3v2 in version 0.13.0 (two release cycle). There are some examples if this in the code base. If you cannot find one, I will point one to you when I am in front of my laptop.

For the documentation I would update whatis in there to say it applies to version spm12 and  more things explaining what people should expect in version aal3v2.

If you have the energy, can you also check how many regions are defined in even older versions of the atlas? (not required but it would be nice 😁).

Don't hesitate to open an early PR in draft mode and we can staet iterating over this.

**Comment by bthirion** [comment]
A PR is welcome indeed !

**Comment by JLefortBesnard** [comment]
Alright, I'm on it :)
