### ISSUE TITLE
modify experimental example `Surface-based first and second level analysis` to show how to project images to volume

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4642]
Current example:

explicitly shows how to use vol_to_surf to project volume on surfaces

https://nilearn.github.io/dev/auto_examples/07_advanced/plot_surface_bids_analysis.html#obtain-automatically-firstlevelmodel-objects-and-fit-arguments

Experimental:

this is now hidden from the example because this is handled by the experimental dataset fetcher

https://nilearn.github.io/dev/auto_examples/08_experimental/plot_new_surface_bids_analysis_experimental.html#obtain-automatically-firstlevelmodel-objects-and-fit-arguments

---

I suggest that maybe we should not have those 'surface' fetchers and always explicitly show in the examples how to project data: this would also make less code to maintain on the fetcher side and would be more didactic for users.

**Comment by bthirion** [comment]
I think that we should show somewhere how to project data, because this is super important BUT I don't think that people should rely systematically on the projection of individual data to fsaverage, as this leads to bad results, doe to fsaverage being quite remote from standard MNI-align brains. Currently, I have no better recommendation than following the standard Freesurfer pipeline. As a reason, I would find it annoying if Nilearn documentation hints that Nilearn surface project would be the way to go.

**Comment by man-shu** [comment]
I think we have resolved this already. So I will close this for now.
