### ISSUE TITLE
Remove the six dependency

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#508]
We cannot depend on six. It is opening a risk of install breakage, with is the thing that we are absolutely trying to avoid.

The easiest way forward is probably to do manually what six does. It's actually suprisingly easy. Joblib does it this way:

* [x] replace all the 'xrange' by 'range'
* [ ] the urlib, StringIO and cPickle moves can be tackled by try/except imports
* [x] the string_types is the hardest. I suspect that it can be handled by something like https://github.com/joblib/joblib/blob/master/joblib/_compat.py
* [x] 'zip(.)' should probably be changed to 'list(zip(.))'

Overall, nothing really hard.

**Comment by AlexandreAbraham** [comment]
> 'zip(.)' should probably be changed to 'list(zip(.))' 

It was already the case almost everywhere...

**Comment by AlexandreAbraham** [comment]
I have done the search & replace modifications.

For the others:
* cPickle is trivial (pickle in p3)
* StringIO is trivial
* urllib seems to be a nightmare. The module tree has been completely changed. It means that we need an if statement for each and every function call. We may be saved by the fact that we use only a small part of it, but we have to keep in mind that adding functionalities may require extra-work because of p3

**Comment by AlexandreAbraham** [comment]
@GaelVaroquaux , could you take a look at #515?

**Comment by GaelVaroquaux** [comment]
Fixed. Excellent work, @AlexandreAbraham ! Thanks.
