### ISSUE TITLE
Issues with the plotting.plot_anat() and plot_roi() function

### ISSUE THREAD

**Issue by Leoniela** [nilearn/nilearn#539]
Hi, 

I have binary lesionfiles of the brain in MNI space and some are not plotted in plt_anat and others are plotted weirdly with plt_roi.

To visualize I put it in NBviewer:
http://nbviewer.ipython.org/gist/Leoniela/c475985613e456950a30

Does anyone have an idea why that is? Is something weird with the files?

Thank you, Leonie

**Comment by banilo** [comment]
Appears to be related to #473 and #537

**Comment by bthirion** [comment]
On 13/04/2015 19:49, Leonie Lmape wrote:
>
> Hi,
>
> I have binary lesionfiles of the brain in MNI space and some are not 
> plotted in plt_anat and others are plotted weirdly with plt_roi.
>
> To visualize I put it in NBviewer:
> http://nbviewer.ipython.org/gist/Leoniela/c475985613e456950a30
>
> Does anyone have an idea why that is? Is something weird with the files?
>
I guess that the main issue comes from data type.
Also, as far as I can see, the images do not seem to be in MNI space (or 
written with a wrong affine), which explains the weird display with 
plot_rois.
If you can share a couple of images, we might give you better indications.
Best,

Bertrand

**Comment by GaelVaroquaux** [comment]
Hi Leonie,

You have multiple problems. One is a bug in our code: that plot_stat_maps
does nto like binary maps. This is fixed in our development version, and
we will release soon. The other is that you are using maps that are not
normalized in MNI space. Thus the plot_roi is giving you a strange
background.

I am closing this issue to avoid poluting our issue tracker, but we must
really make a release. Once we have done a release (give us a week or
so), you will be able to update by running "pip install -U --user
nilearn".

**Comment by Leoniela** [comment]
Thank you for you answers!
Concerning my maps and MNI space - The MNI template I have registered it to was reoriented. So the files basically are in MNI space just with different orientation.
