### ISSUE TITLE
Add a pointer to the docs built by circle-ci for people to see latest build docs

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#690]
I am not sure where we should be putting this. Maybe in the readme, fairly down the line.

Or we should create a 'CONTRIBUTING.md' in which we give contributor instructions, and that github will pick up automatically?

**Comment by thomasbazeille** [comment]
I think that @kchawla-pi solved something related recently, am I wrong ?

**Comment by kchawla-pi** [comment]
On the contrary, Gael implemented it and I might have broken it.

**Comment by emdupre** [comment]
I think this can be closed in favor of #2355, no ?

**Comment by thomasbazeille** [comment]
@kchawla-pi can you point me to the "tinkering", we'd need this running

**Comment by kchawla-pi** [comment]
The tinkering was - I suspect - that I replaced the old CircleCI setup with webhooks with the Github Marketplace App (which has webhooks pre-included). I speculate the Artifacts direct link stopped working then. It might be because the CircleCI token that Gael's Artifact PR used was changed in the process.

**Comment by kchawla-pi** [comment]
All this is my speculation because I didn't expect this to break at all. I was surprised when it did.
