### ISSUE TITLE
Access to member 'last_log_lik' before its definition line 821

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#744]
#### Occurred on:
- **Commit**:  c7af1f34d7cbecf347b3039f962b33980e226265
- **File**:    [nilearn/group_sparse_covariance.py](https://github.com/nilearn/nilearn/blob/c7af1f34d7cbecf347b3039f962b33980e226265/nilearn/group_sparse_covariance.py)
- **LineNum**: [815](https://github.com/nilearn/nilearn/blob/c7af1f34d7cbecf347b3039f962b33980e226265/nilearn/group_sparse_covariance.py#L815)
- **Code**:    `if iter_n > -1 and self.last_log_lik > log_lik:`
#### Currently on:
- **Commit**:  5b5d8d206c03c3c65ee22896d2850bbb886b333a
- **File**:    [nilearn/group_sparse_covariance.py](https://github.com/nilearn/nilearn/blob/5b5d8d206c03c3c65ee22896d2850bbb886b333a/nilearn/group_sparse_covariance.py)
- **LineNum**: [816](https://github.com/nilearn/nilearn/blob/5b5d8d206c03c3c65ee22896d2850bbb886b333a/nilearn/group_sparse_covariance.py#L816)

This is something I noticed in landscape.io ages ago, creating an issue for this so we don't forget about it.

**Comment by tsalo** [comment]
It looks like this would only raise an exception if `EarlyStopProbe` _isn't_ called with `iter_n <= -1` its first time. Since calling with `iter_n = -1` is hard-coded into `_group_sparse_covariance()` (see below), I don't think that's a problem. Unless this is specifically a linting issue?

https://github.com/nilearn/nilearn/blob/c10248e43769f37eaea804f64d44a7816e3c6e03/nilearn/connectome/group_sparse_cov.py#L279-L282

**Comment by bthirion** [comment]
Agreed.

**Comment by bthirion** [comment]
Closing, then.
