### ISSUE TITLE
Encoding dataset / example? Kay et al. (2008)

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#776]
I just read Naselarise et al. (2011) about encoding vs. decoding--I'm sure people here are familiar with it. They advocate for experiments to target encoding models, and to derive decoding models via Bayes rule.

Encoding models include a Gabor jet (Kay et al., 2008), Semantic features (Naselarise et al., 2009), and later features from ConvNets (Agrawal et al., 2014). A recent paper from JoN (Guclu & van Gerven, 2015) used an encoding model based on a ConvNet to try and associate voxel responses to layers of the neural network, with a goal similar to work I saw @eickenberg present at OHBM 2015.

I believe the Kay and Naselarise data are publicly available (http://crcns.org/data-sets/vc/vim-1/about-vim-1), and there may be relevant code available (perhaps in MATLAB: http://cvnlab.net/resources.html).

Seems a nice complement to the decoding work here to have an encoding example, and do the simple Bayes rule computation to create the decoding model. A bit of work, but what do you think?

**Comment by eickenberg** [comment]
Would be lovely indeed. I would have made one long ago if the website hosting the data weren't so locked down. Unfortunately you need a verified login for crcns in order to download any data. Although one could create downloaders that actually do the login process given the credentials, I believe that the nilearn policy for downloaders is that the data should be directly/easily downloadable, as is the case with the datasets from openfmri for example.

I think this is the only blocker. Otherwise an example would be really nice to have.

**Comment by GaelVaroquaux** [comment]
> I just read Naselarise et al. (2011) about encoding vs. decoding--I'm sure
> people here are familiar with it.

We are. It's a great paper.

An example going in this direction (with the associated data downloader
would be awesome). It's a fair amount of work.

**Comment by AlexandreAbraham** [comment]
If the license allow it, we can host it on NITRC. Otherwise, in a first time, you can submit it to nilearn_sandbox. Then we'll see how to move it to nilearn.

**Comment by eickenberg** [comment]
> If the license allow it, we can host it on NITRC.

I don't recall this being clearly stated positively anywhere. (So usually
that means negative, right?)
Neither is there a clear (global) licensing document anywhere on crcns as
far as I remember (I think I asked at some point).

**Comment by eickenberg** [comment]
I'd be more than happy to review this / give suggestions / help out

**Comment by da5nsy** [comment]
Hey folks, did this lead anywhere?
I'm a student of Neuromatch Academy and an implementation of Kay et al. (2008) would be very handy to us right now.
Otherwise, give us a couple of weeks(?) and we might have something to contribute.

**Comment by eickenberg** [comment]
I don't think so. The main snag was that this dataset is behind a login
wall and intended to be behind a login wall, making an automated login-free
downloader impossible.

Since datalad now exists and can download from CRCNS (
http://datasets.datalad.org/?dir=/crcns) this project could be attempted,
iff it is OK to 1) use datalad in the example script and 2) have the
example ask for login credentials

**Comment by jeromedockes** [comment]
eickenberg <notifications@github.com> writes:

> I don't think so. The main snag was that this dataset is behind a login
> wall and intended to be behind a login wall, making an automated login-free
> downloader impossible.
>
> Since datalad now exists and can download from CRCNS (
> http://datasets.datalad.org/?dir=/crcns) this project could be attempted,
> iff it is OK to 1) use datalad in the example script and 2) have the
> example ask for login credentials
>

I think that would be a recurrent source of problems for the continuous
integration. More generally, we would like to reduce the number of data
downloaders because they require a lot of maintenance.

**Comment by bcipolli** [comment]
Have y'all thought about splitting the data downloaders off to a separate
repo? I started this in the past, it seemed like the right idea.

**Comment by jeromedockes** [comment]
> Have y'all thought about splitting the data downloaders off to a separate
> repo? I started this in the past, it seemed like the right idea.

I think the main reason for having the downloaders is because we need
the data to build the example gallery (to showcase other nilearn
features) in the continuous integration. Whether it is in the same or a
separate repo a failing download would be a problem for nilearn
maintenance. I'm not sure how moving the downloaders to a separate repo
would help? Moreover, this might introduce more work to handle
compatibility with different versions of the data downloaders library.

**Comment by da5nsy** [comment]
I think the access requirements for the Kay data have changed recently, possibly for [NMA](https://www.neuromatchacademy.org/). The pre-processed data is now on [osf](https://osf.io/r638s) and a [loader script](https://github.com/NeuromatchAcademy/course-content/blob/master/projects/load_kay_images.ipynb) exists (the name is misleading, this loads both images *and* data). There's also a [video introduction](https://www.youtube.com/watch?v=LdJkLyw4yzg&feature=youtu.be) to the data.

We're [working on](https://github.com/da5nsy/ReplicatingKay2008) a replication currently, with a deadline of end of next week.

**Comment by eickenberg** [comment]
> I think the main reason for having the downloaders is because we need
> the data to build the example gallery (to showcase other nilearn
> features) in the continuous integration.

Right, that is indeed a problem. Though there may be a way of storing login information in an environment variable on the CI and somehow feeding it to a downloader, making the example runnable in CI while not compromising the login wall globally. But even then, the additional traffic might make the testing time out in case there are already time budget constraints.

> I think that would be a recurrent source of problems for the continuous
> integration. More generally, we would like to reduce the number of data
> downloaders because they require a lot of maintenance.

I totally 💯 percent get the point about data downloader maintenance.
However on the other hand, it is worth pointing out that this dataset is the archetype of naturalistic fmri experiment, unparalleled to this day in functional SNR for static images, and has clearly stood the test of time. It is a sort of CIFAR10 for encoding models and reconstruction.
Seen from that angle, it might be worth considering adding some very standard examples using it, especially the analysis from the original paper.

It's obviously a trade-off and I completely understand decisions in either direction

**Comment by jackgallant** [comment]
Hi Folks:

**Comment by eickenberg** [comment]
Make sure that if you do host this dataset somewhere else that you do not use the one hosted for NMA -- it only contains ~8k voxels, whereas the original preprocessed dataset has ~21k voxels. I suspect that the 8k voxels are those with ROI labels. But there are quite a few voxels without ROI labels that respond to the stimulus.

**Comment by emdupre** [comment]
Thank you for the insight, @jackgallant ! I'm having a bit of trouble confirming -- do you know what the dataset is licensed under ? I think we'd need to know the license to re-host on e.g. OSF.

Otherwise, thank you for the pointer to the derivatives, @da5nsy ! I don't think we'd want to include a fetcher for these (they're a step or two further along in pre-processing than e.g. the NiftiMasker is designed to work with), but that they've been hosted there is promising for licensing.

Regarding the more general discussion of data fetchers: this has come up in a few places, and I think the current general agreement is that we'd like to add new data fetchers at the rate which we remove older ones. So, if there are specific, existing data sets that this one could replace, it'd be great to point to those !

**Comment by jackgallant** [comment]
AFAIK the data on CRCNS are posted under some form of open attribution license, but sadly I am not sure. If you do repost the data please be sure to post ALL of the data. Someone mentioned that the OSF data set is not complete.

**Comment by eickenberg** [comment]
> further along in pre-processing than e.g. the NiftiMasker is designed to work with

For this dataset both raw and preprocessed data are available. However, I would strongly recommend using the preprocessed data, unless somebody has a lot of time to perform all the preprocessing involved (it requires doing a FIR GLM with AR(n) noise model -- potentially interesting for when nistats gets integrated, but guaranteed not a straightforward task)

This example here, 
http://nilearn.github.io/modules/generated/nilearn.datasets.fetch_miyawaki2008.html
also does not start from maskers I believe.

> add new data fetchers at the rate which we remove older ones

Regarding this policy, maybe the miyawaki dataset above is the MNIST of encoding models if vim-1 is the CIFAR10. One could decide to supersede miyawaki with kay2008, but it is true that the miyawaki dataset, given that it operates on only 10x10 pixels, lends itself to simpler direct decoding approaches

**Comment by bthirion** [comment]
> Regarding this policy, maybe the miyawaki dataset above is the MNIST of encoding models if vim-1 is the CIFAR10. One could decide to supersede miyawaki with kay2008, but it is true that the miyawaki dataset, given that it operates on only 10x10 pixels, lends itself to simpler direct decoding approaches

I agree with that. To me it's fine to have a project based on nilearn running encodinganalyses on vim-1, I'm less sure that this is a good choice for Nilearn. 
Thx to all of you for the suggestion and discussion !

**Comment by GaelVaroquaux** [comment]
> I totally 💯 percent get the point about data downloader maintenance. However on the other hand, it is worth pointing out that this dataset is the archetype of naturalistic fmri experiment, unparalleled to this day in functional SNR for static images, and has clearly stood the test of time. It is a sort of CIFAR10 for encoding models and reconstruction.

Still, at the end of the day, data download is a major burden for nilearn
maintenance, as it makes the build of the docs and examples fragile.

The data downloaders in nilearn are there to enable demo and teaching,
not state-of-the-art research. The data needs to be minimalistic.

**Comment by eickenberg** [comment]
I think the data downloader burden argument holds and can be the sole
reason not to include this relatively heavy dataset.

I do not think that one can still do state-of-the-art research with it, and
I do think that it would lend itself to some great demos and teaching. But
those can easily be hosted somewhere else.

**Comment by bthirion** [comment]
We have reached a consensus. CLosing.
