### ISSUE TITLE
`cut_coords` is not clear for new users

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#812]
Some users complained about the fact that it is not possible to chose the location for the cut in plotting functions. It turns out that they did not know about `cut_coords`.

Also, for them, the `display_mode` is not clear. For example, they don't understand why they have to pass only 2 coordinates when using 'xz'.

**Comment by KamalakerDadi** [comment]
I have this in my mind since long time. The answer would be to explain all this unclear things with a very clear and good example. I realised this when I addressing simple issue related to ```n_cuts```

**Comment by lesteve** [comment]
I thought what @AlexandreAbraham had in mind was to allow to pass cut_coords as list of 3d coordinates irrespective of the display_mode. This way you can change the display_mode without having to worry about changing cut_coords.

**Comment by alexsavio** [comment]
Related to this, is there any way to plot in a grid instead of a row?
I mean, if I use cut_coords=40, I wouldn't like to plot 40 slices in a row, but maybe a grid of 5x8 slices.
I was thinking that an argument, e.g., `plot_grid=(5, 8)`, would help, if there is no other way to do this.
I have been trying to implement something like this for a while, if you indicate me what should be changed, I could do it.

P.S.: I know that I have another open issue, but this is more urgent for me, I will arrive to the other one one day.

**Comment by GaelVaroquaux** [comment]
> Related to this, is there any way to plot in a grid instead of a row?

No. It would be nice, but it's a significant amount of work (requires
reworking the positionning code), and given that it is a fairly low
return over investment, our priori cannot be there for now.

**Comment by alexsavio** [comment]
Do you think this will overcomplicate the code base? This is a feature I feel like doing, I will have a look through the code to have an estimate.
