### ISSUE TITLE
Avoid documentation rot in continuous integration

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#862]
I have just added a 'make check' target to the doc Makefile. It fails when there is a warning in the docs.

I have also fixed all the warnings (hours of work :( ).

I think that we should add "make check" as a test on circleci. It needs to be done after we build the docs, as the examples need to be run for warnings to pass.

@jnothman : we might be interested in porting "make check" to scikit-learn, and the CI test too, if the experiment in nilearn is successful. It's been such a fight with warnings in the scikit-learn docs.

**Comment by aabadie** [comment]
I had a look at this one and I'm about to have something fully working on circle ci.

Here are my conclusions:
* make -C doc check requires packages to be installed on the Ubuntu VM (12.04): dvipng.
* installing extra packages was broken on the VM but I could fix the issue by removing the conflicting latex package (texlive-binaries).
* I'm now trying the identify the missing packages in order to have the full doc check running.

As I had problems with circle-ci at the beginning, I also tried to run the doc check on travis and noticed a few things:
* I couldn't succeed because of the output limit (4MB) being reached by the full test suite (including doc test/check).
* At the beginning I reached several times the maximum resources provided by the legacy infrastructure of travis-ci. I gave a try to the container based one using : `sudo: required` in the `.travis.yml` configuration file. It works. The container infrastructure should be faster (that's what travis-ci claims). Maybe this change can be part of another PR.

**Comment by lesteve** [comment]
> sudo: required in the .travis.yml configuration file. It works. The container infrastructure should be faster (that's what travis-ci claims). Maybe this change can be part of another PR.

The only reason we have to stick with the legacy Travis infrastructure is because we want to add neurodebian to the apt sources. For us to move the container-based one, we need Travis to add neurodebian to a white list. It hasn't happened and it is not clear whether/when it will. The PR on the travis repo is https://github.com/travis-ci/apt-source-whitelist/pull/10.

**Comment by aabadie** [comment]
> For us to move the container-based one, we need Travis to add neurodebian to a white list.

That's the purpose of using `sudo: required` in the travis configuration file. It gave the best of both world: one can use `sudo` (use in neurodebian setup script) and switch to the container infrastructure.

**Comment by lesteve** [comment]
> That's the purpose of using sudo: required in the travis configuration file.

:confused: If I am reading the docs correctly:
https://docs.travis-ci.com/user/workers/container-based-infrastructure
https://docs.travis-ci.com/user/workers/standard-infrastructure/

we are using the default (which is the same as sudo: required) i.e. going to the legacy infrastructure.

**Comment by aabadie** [comment]
> we are using the default (which is the same as sudo: required) i.e. going to the legacy infrastructure.

Indeed, I got confused by the error messages returned by circle ci. Now my understanding is that if you set `sudo: false` one time in your `travis.yml file`, later you have to explicitly set the legacy infrastructure using `sudo: required`, otherwise it uses the container infrastructure (even without the `sudo:false` in the configuration file).

**Comment by lesteve** [comment]
> Indeed, I got confused by the error messages returned by circle ci

Hopefully you mean Travis here ...

> Now my understanding is that if you set sudo: false one time in your travis.yml file, later you have to explicitly set the legacy infrastructure using sudo: required, otherwise it uses the container infrastructure (even without the sudo:false in the configuration file).

Hmm slightly weird, but this may be Travis way of changing the default infrastructure on a per-project basis. I am guessing you are talking about Travis building on your branches from aabadie/nilearn otherwise I am a bit lost.

**Comment by aabadie** [comment]
> Hopefully you mean Travis here ...

Yes sorry

> Hmm slightly weird, but this may be Travis way of changing the default infrastructure on a per-project basis. I am guessing you are talking about Travis building on your branches from aabadie/nilearn otherwise I am a bit lost.

Exactly I tried on a personnal project in order to avoid polluting the upstream repo.

**Comment by lesteve** [comment]
> Exactly I tried on a personnal project in order to avoid polluting the upstream repo.

OK that's what I thought. This may be useful to remember if we ever switch back and forth with nilearn/nilearn.
