### ISSUE TITLE
Data returned by _safe_get_data is copied.

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#956]
In the code, the data returned by `_safe_get_data` is sometimes copied. I expected `_safe_get_data` to return a copy of the data. We should check that this copy is necessary.

**Comment by banilo** [comment]
> We should check that this copy is necessary.

+1

**Comment by NicolasGensollen** [comment]
Indeed, `_safe_get_data`  returns a copy of the data only when the `img` argument has a `None` `_data_cache` argument:

https://github.com/nilearn/nilearn/blob/d1a2563cbf10c1470835b04bbc6e7d627d71019a/nilearn/_utils/niimg.py#L44-L52

When this isn't the case, `_safe_get_data` behaves likes `_get_data` (with NaNs handling).

I see several options:

1- do nothing and keep this behavior
2- implement a consistent behavior: it should either always return a copy of the data, or never. 
3- add a `copy` parameter (defaulting to `False`) to either always copy the data or never

Since other parts of the code explicitely assume that `_safe_get_data` does not copy the data, like the `threshold_img` function:

https://github.com/nilearn/nilearn/blob/ddc59b147eecc6b8d7619edd9a1eba7f6487fec5/nilearn/image/image.py#L818-L822

I wouldn't go for a solution 2 with always copying.

WDYT?

**Comment by bthirion** [comment]
My impression is that you made the right choice.

If nobody comes with another unforeseen use case, I'll be happy with #2634.

**Comment by NicolasGensollen** [comment]
Closing since #2634 was merged...
