### ISSUE TITLE
Add more saving of outputs in examples

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#958]
Examples should almost always save outputs (and sometimes intermediate results), as this is what end-users want to do.

We have to keep in mind that many end-users learn to use Python for neuroimaging why nilearn, so they have no idea how to save things. In addition, they learn by copy-pasting the examples, for the better or the worst.

**Comment by AlexandreAbraham** [comment]
Doesn't it conflict with sphinx behavior?

**Comment by GaelVaroquaux** [comment]
> Doesn't it conflict with sphinx behavior?

I don't think so, it's just a few
"component_img.savefig('components.nii.gz')"
at the right place in the examples.

**Comment by AlexandreAbraham** [comment]
Oh, OK, you were talking about the nifti files. I was thinking of the figures.

**Comment by GaelVaroquaux** [comment]
> Oh, OK, you were talking about the nifti files. I was thinking of the figures.

Indeed niftifiles

**Comment by banilo** [comment]
> end-users

What's the difference between a user and an end-user?

**Comment by banilo** [comment]
+1 on more explicit saving to disc. I would also think that a) plotting (for paper) and b) dumping (to further inspect in Mango/Fslview etc.) are the main meta aims of the baseline end-user.

**Comment by GaelVaroquaux** [comment]
>     end-users

> What's the difference between a user and an end-user?

I personnaly make no difference :)

**Comment by GaelVaroquaux** [comment]
> I would also think that a) plotting (for paper) and b) dumping (to
> further inspect in Mango/Fslview etc.) are the main meta aims of the
> baseline end-user.

Yop!

**Comment by sahmed95** [comment]
I was checking out the examples and found that the basic nilearn example has the following line for saving nifti files - "smooth_anat_img.to_filename('smooth_anat_img.nii.gz')". 

1. Does this PR intend to have more such intermediate saving of nifti files in the examples? Or [plotting example page](http://nilearn.github.io/plotting/index.html#plotting)
 
2. For saving of images(for paper) a direct plt.savefig() should also work right ? I am asking this since I saw in nilearn/nilearn/plotting/img_plotting.py there is seperate function defined as plotting.show() but nothing as plotting.savefig()

**Comment by GaelVaroquaux** [comment]
plotting.savefig saves a 

The goal of this issue is to have saving of nifti files, with the "to_filename" method, while the savefig is for saving figures, which is not really the topic here.

**Comment by sahmed95** [comment]
@GaelVaroquaux Ok. I 'll work on saving nifti files then :-)

**Comment by bthirion** [comment]
I think this one is deprecated.
