### ISSUE TITLE
Code coverage broken on coveralls

### ISSUE THREAD

**Issue by aabadie** [nilearn/nilearn#960]
The global and per file coverage statistics are working on coveralls but one cannot have access to the lines covered/not covered in each file.
To me the file path is not correct: it contains the full path whereas it should only be the relative path.
Example:
`nilearn/tests/test_testing.py`
instead of
` /home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nilearn-0.2.1-py3.5.egg/nilearn/tests/test_testing.py `

**Comment by lesteve** [comment]
Yeah this is because we cd outside the git repo before running the tests in order to make sure that setup.py does have all the data_package correctly defined. Otherwise you can end up with all your CI tests working but your package on PyPI broken.

I think I have managed to do set it up correctly via the coveralls website in the past. The annoying thing is that you need to redo it for each release. Last time I tried I couldn't get it to work IIRC.

As an alternative, you could either run nosetests locally with --cover-html. It will generate an html that will show you which lines are not covered.

**Comment by lesteve** [comment]
@aabadie I tweaked the coveralls config on coveralls, it seems to work for me now. That'd be great if you could double-check and close the issue if that's the case for you too.

**Comment by GaelVaroquaux** [comment]
> @aabadie I tweaked the coveralls config on coveralls, it seems to work for me
> now.

Thanks. It would be great if you could document this somewhere (like in a
README_development.rst, or any other place you think is relevant).

**Comment by lesteve** [comment]
Maybe adding a rst file in doc/developers ? There is already something there about group_sparse_covariance.

**Comment by aabadie** [comment]
> I tweaked the coveralls config on coveralls, it seems to work for me now.

It works now. What did you change on the configuration ?

> Maybe adding a rst file in doc/developers ?

That's an idea. There's already an issue for this (#891), maybe this could be discussed there.

**Comment by GaelVaroquaux** [comment]
+1
