### ISSUE TITLE
nan values are returned by csv_to_array

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#974]
```python
from nilearn import datasets
from nilearn._utils.numpy_conversions import csv_to_array

atl = datasets.fetch_atlas_msdl()
csv_to_array(atl.labels) # nans

csv_to_array(atl.labels, dtype=None) # no nans
```
I am not sure whether it is an issue or upto user to use ```dtype=None```

**Comment by AlexandreAbraham** [comment]
`csv_to_array(atl.labels, dtype=None) # no nans`

No nans but all columns are string because of the top columns.

`csv_to_array(atl.labels, dtype=None, names=True)`

is actually the way to go.

`csv_to_array` is not magic: it is a wrapper around `np.genfromtxt` that will handle several *delimiters*. It does not automatically handle different *types* of data.

I think that we should:

* never return a path to a csv file but load it
* decide if we want to expose a user-friendly function to load CSVs. I think we shouldn't spend time on this. If people have trouble opening CSVs, we can point them to pandas.

**Comment by GaelVaroquaux** [comment]
>   • decide if we want to expose a user-friendly function to load CSVs.
>     I think we shouldn't spend time on this. If people have trouble
>     opening CSVs, we can point them to pandas.

We don't want a user-friendly function to load CSVs. We want to point
people to pandas, as this is what will make them independent and will
allow them to feel the power of Python.

**Comment by AlexandreAbraham** [comment]
In that case, since this function is just for us, I suggest that we leave it as it is.
